### ISSUE TITLE
StarDist (2D) on GPU in Exclusive Process mode

### ISSUE THREAD

**Issue by dsethz** [stardist/stardist#102]
Hey,

congratulations on a cool publication!

I want to test `StarDist2D` on a cluster that runs GPUs in Exclusive Process mode. When, for example, running [notebook 2](https://github.com/mpicbg-csbd/stardist/blob/master/examples/2D/2_training.ipynb), I am thrown this error:

`tensorflow.python.framework.errors_impl.InternalError: CUDA runtime implicit initialization on GPU:0 failed. Status: all CUDA-capable devices are busy or unavailable`

. I assume this error occurs, because two processes are supposed to run on the same GPU (1. model training, 2. `gputools`-based image processing). I am currently confirming if I can turn off the Exclusive Process mode (my guess is "no"), but I was hoping that there may also be a solution on the `StarDist`-level?

Best,
D

**Comment by maweigert** [comment]
Hi, 

This does look more like a CUDA related issue (rather than stardist or gputools)

You could try the following

1) Check whether your GPU is not already allocating all memory (e.g. via `nvidia-smi`) 

2) Restrict the code to a single GPU, e.g. by putting the following before anything else in your notebook: 

```
import os
os.environ["CUDA_VISIBLE_DEVICES"] = "0"
```

**Comment by dsethz** [comment]
Hey,

Thank you for your feedback.

1. Access to cluster GPUs is handled by IBM LSF (Load Sharing Facility) batch system preventing usage of a GPU by multiple users. The above error is thrown when I initialise the model according to 
```python
In[11]: model = StarDist2D(conf, name='stardist', basedir='models')
````
in [notebook 2](https://github.com/mpicbg-csbd/stardist/blob/master/examples/2D/2_training.ipynb) so GPU memory should not be full.

2. `CUDA_VISIBLE_DEVICES` is handled by the LSF batch system. However, I also manually assigned the `CUDA_VISIBLE_DEVICES` and the error persists.

If I am not mistaking, the above error is expected if we run >1 "independent processes" on a single GPU that is in Exclusive Process mode. Isn't this exactly what `StarDist` does and why we use 

```python
In [10]: if use_gpu:
    from csbdeep.utils.tf import limit_gpu_memory
    # adjust as necessary: limit GPU memory to be used by TensorFlow to leave some to OpenCL-based computations
    limit_gpu_memory(0.8)
```
?

Best,
D

**Comment by uschmidt83** [comment]
> If I am not mistaking, the above error is expected if we run >1 "independent processes" on a single GPU that is in Exclusive Process mode.

I have no experience with "Exclusive Process mode" and wouldn't even know how to reproduce this. Does it work under the same conditions but without this mode?

**Comment by dsethz** [comment]
Hey,

The [Exclusive Process mode](https://docs.nvidia.com/deploy/mps/index.html#topic_3_3_1_2) allows only one process at a time on a GPU and can be enabled like [this](https://docs.nvidia.com/deploy/mps/index.html#topic_5_1_3). Can you reproduce the error when enabling the Exclusive Process mode?

I cannot test `StarDist` in default mode since I am working on a cluster that uses Exclusive Process mode to ensure that GPUs are correctly assigned to users. 

Best,
D

**Comment by maweigert** [comment]
You are running the notebooks on the cluster? Can you post the output of `nvidia-smi` right after starting the notebook (before importing anything)?

**Comment by dsethz** [comment]
To be exact, I omitted all commands that are notebook specific 

(e.g. 
```python
%matplotlib inline
%config InlineBackend.figure_format = 'retina'
```
)
and copy-pasted the rest to a script, which I submit as a batch job to the cluster. This is the output of `nvidia-smi` if run before the script:

```bash
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 418.39       Driver Version: 418.39       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce RTX 208...  Off  | 00000000:3E:00.0 Off |                  N/A |
|  0%   39C    P8     3W / 250W |      0MiB / 10989MiB |      0%   E. Process |
+-------------------------------+----------------------+----------------------+
   ¦ ¦ ¦ ¦ ¦ ¦ ¦ ¦ ¦ ¦ ¦ ¦ ¦ ¦ ¦ ¦ ¦ ¦ ¦ ¦                
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

Not sure how to call `nvidia-smi` from within a script, but I guess this question was more related to running [notebook2](https://github.com/mpicbg-csbd/stardist/blob/master/examples/2D/2_training.ipynb) as a notebook.

Best,
D

**Comment by dsethz** [comment]
Hey again,

Sorry to bug again, but were you able to reproduce the issue in Exclusive Process mode?

Best,
D

**Comment by dsethz** [comment]
Have you had the chance to test stardist in Exclusive Process mode?

**Comment by maweigert** [comment]
Hi @dsethz ,

sorry for the late response. 

I cannot reproduce this bug, i.e. the following runs fine for me:

1) Setting cuda to exclusive mode:

```
sudo nvidia-smi -c 3
```

2) Importing a pretrained model

```
from stardist.models import StarDist2D

model = StarDist2D.from_pretrained('2D_versatile_fluo')
```

Does this throw an error for you?

**Comment by dsethz** [comment]
Hey @maweigert,

Thank you for testing. According to the [nvidia-manual](https://docs.nvidia.com/deploy/mps/index.html#topic_5_1_3):

```bash
sudo nvidia-smi -i 0 -c EXCLUSIVE_PROCESS
```
will set GPU 0 to exclusive process mode. I currently do not have access to a GPU-machine on which I can run as super-user, so I cannot test if

```bash
suda nvidia-smi -c 0
``` 

would do the trick, too. 

Regarding 2.: No, it does not throw an error. 

Best,
D

**Comment by dsethz** [comment]
Hey @maweigert,

Does stardist run correctly with 

```bash
sudo nvidia-smi -I 0 -c EXCLUSIVE_PROCESS
```

on GPU 0?

**Comment by maweigert** [comment]
Hi @dsethz ,

Sorry for the late reply. 

I can reproduce that training a stardist model with `use_gpu=True` (i.e. with OpenCL accelerated batch generation) in `EXCLUSIVE_PROCESS` mode fails. I think the only way around is to set `use_gpu=True` in the config (note that this only affects the batch generation, not the training), as Exclusive mode will by design exclude opencl from acquiring a valid second context on the GPU. 

Hope that helps,
Martin
