### ISSUE TITLE
StopIteration error with certain image shape

### ISSUE THREAD

**Issue by Romain-Laine** [stardist/stardist#117]
Hi all,
I have been using StarDist 2D with a range of image shapes and have noticed that for certain image shapes, I get a StopIteration error right when the last epoch finishes (see below when running training for 5 epochs for instance).
The error below occurs if I use images of the shape (698, 788) and patch sizes of 672. But it does not occur if I manually crop these same images to (672, 672) prior to training. 
Any idea why that is? It would be helpful to allow any image shape input to the image generator.
Many thanks !

Romain

<img width="1386" alt="Screenshot 2021-02-22 at 13 21 21" src="https://user-images.githubusercontent.com/21193399/108714119-0c870080-7511-11eb-971c-526870ccf007.png">

**Comment by maweigert** [comment]
Hi @Romain-Laine,

Thanks for the report - this does indeed sound very strange. Could you post a little minimal example (e.g. with empty images) that reproduces this behavior? Thanks!
M

**Comment by Romain-Laine** [comment]
Hi Martin,
Thanks for your reply. I have created the following dataset for instance:
https://www.dropbox.com/sh/l3jyfyiv413p8ul/AADiJI2RZtFlshmaMDOTyf1Ba?dl=0
Using this for training produces the error mentioned above. All default parameters. But any parameters seem to raise that issue anyway. We currently run our notebook on TF1.15.2

I hope this helps. Please let me know if you need any other info.
Best,

Romain

**Comment by maweigert** [comment]
Hi Romain,

Can you post a minimal code example that shows the error? 
E.g. the following works fine for me

```
from stardist.models.model2d import Config2D, StarDist2D
import numpy as np

# create empty dummy data
X = np.zeros((8,698,788), np.float32)
Y = X.astype(np.uint16)

model = StarDist2D(Config2D(),None,None)
model.train(X,Y,validation_data=(X,Y), epochs=5)


```

**Comment by Romain-Laine** [comment]
Hi Martin,
It's using our ZeroCostDL4Mic notebook that you can find right here:
https://colab.research.google.com/github/HenriquesLab/ZeroCostDL4Mic/blob/master/Colab_notebooks/StarDist_3D_ZeroCostDL4Mic.ipynb
And all default parameters. 
Otherwise I can list the parameters used for you. Let me know!

Many thanks!

Romain

**Comment by uschmidt83** [comment]
Dear Romain,

I cannot reproduce this error, neither with tensorflow 1.15.3 nor tensorflow 2.3.1.


> It's using our ZeroCostDL4Mic notebook that you can find right here:
> https://colab.research.google.com/github/HenriquesLab/ZeroCostDL4Mic/blob/master/Colab_notebooks/StarDist_3D_ZeroCostDL4Mic.ipynb
> And all default parameters.

As Martin said, please provide us with a [minimal example](https://en.wikipedia.org/wiki/Minimal_working_example) that reproduces the error. I.e. make a copy of your notebook and remove everything that isn't necessary to cause this error. This will require some effort on your end, but we don't have the time to debug everyone's problems.

Furthermore, I'm confused that you posted a link to the *3D* StarDist ZeroCost notebook. I thought you wanted to do 2D?

Uwe

**Comment by Romain-Laine** [comment]
Hi guys, 
Apologies for posting on the wrong repo! I will transfer.
Yes, I will prepare a minimal code example and come back to you asap. I do not expect you to debug our code, apologies if that came across this way.
Thanks a lot.

Best,

Romain

**Comment by Romain-Laine** [comment]
Hi guys,
I finally found the time to get back to this issue and realised that I had set the number_of_steps as a non-integer value by mistake. This caused the problem. I have now fixed this in my code.
Many thanks for your patience!

Best,

Romain

**Comment by maweigert** [comment]
Hi @Romain-Laine,

Ah, I see :) Thanks for letting us know!
