### ISSUE TITLE
How to compute Params(M) and FLOPs(G) of StarDist.

### ISSUE THREAD

**Issue by pzSuen** [stardist/stardist#123]
Hello, thanks for your great work of StarDist.

We want to contrast the Params(M) and FLOPs(G) of StarDist and our model.
StarDist is built by Tensorflow, but ours is by Pytorch.

**I want to ask if there a way to compute Params(M) and FLOPs(G) of StarDist?**

Thank you!

**Comment by maweigert** [comment]
You can print a summary of the keras model with `model.keras_model.summary()` which includes the number of parameters.

**Comment by pzSuen** [comment]
Thank you, 
I get the Prams in this way, but how to compute the FOLPs？

**Comment by uschmidt83** [comment]
Hi @pzSuen,

> I want to ask if there a way to compute ... FLOPs(G) of StarDist?

I've never done this (and don't need this), but google found this: https://pypi.org/project/keras-flops/
