### ISSUE TITLE
notebook error after GPU sync failed (CUDA driver version is insufficient for CUDA runtime version)

### ISSUE THREAD

**Issue by MicPhotonIGBMC** [stardist/stardist#129]
Hi,

The issue does happen each time after a "GPU sync failed" error while training stardist 3D, both 2D and 3D training notebook are throwing the following error when runnign the cell "model = StarDist2D(conf, name=‘stardist’, basedir=‘models’)"

**OUTPUT =** InternalError: cudaGetDevice() failed. Status: CUDA driver version is insufficient for CUDA runtime version

The current work around I have found is to re-install CUDA Toolkit.

**Config:**
In anaconda 4.9.2, I created a stardist environment with
python=3.8
tensorflow-gpu=2.3.0.
CUDA toolkit 10.1 (no pyopencl/gputools installation). Paths are set in the environment variables

I have also posted this issue on image.sc (https://forum.image.sc/t/gpu-acceleration-works-only-on-first-run-stardist-jupyter-notebook/50629) with the error logs.

Any suggestions?

Bertrand

**Comment by maweigert** [comment]
Solved according to OP (https://forum.image.sc/t/gpu-acceleration-works-only-on-first-run-stardist-jupyter-notebook/50629/6)
