### ISSUE TITLE
Possible mix up of (dy,dx) in star_dist computation

### ISSUE THREAD

**Issue by codingS3b** [stardist/stardist#132]
After looking at your code for the computation of the star distance that you describe in the paper, I was wondering about the lines [here and the following](https://github.com/stardist/stardist/blob/810dec4727e8e8bf05bd9620f91a3a0dd70de289/stardist/geometry/geom2d.py#L46) regarding the direction of growth. 
From [trigonometry on the unit circle](https://en.wikipedia.org/wiki/Unit_circle), shouldn't that be the other way around, i.e.

```
dx = cos(phi)
dy = sin(phi)
```
?
Maybe I'm not completely understanding the algorithm yet or have mixed up dimensions myself. Anyway, I would be happy if you could clarify this a bit.
Thanks!

**Comment by maweigert** [comment]
Hi @codingS3b ,

In the code above, "x" and "y" refer to the first and second dimensions/axis respectively, which is the opposite of the usual semantic I admit :) We maybe should rename that at one point...
