### ISSUE TITLE
Further Training of a Completed StarDist 3D Model

### ISSUE THREAD

**Issue by michaelschwimmer** [stardist/stardist#134]
Hello!
I was wondering if there was a way to resume training of a model that is already finished? I know that with keras, you can resume training by specifying a start epoch, but I'm not sure how to implement this with stardist? 

Thank you and best wishes!

Michael Schwimmer

**Comment by maweigert** [comment]
Hi @michaelschwimmer ,

you can always call `model.train` even after having loaded it from an old checkpoint. The only drawback that I currently see, is that the tensorboard output will reset its epoch and thus will be a bit confusing.
