### ISSUE TITLE
False positive prediction at Image border

### ISSUE THREAD

**Issue by codingS3b** [stardist/stardist#148]
We are segmenting bubbles and it works very well with stardist. We just observed that occasionaly stardist predicts instances at the corners of the cylinder where the bubbles are contained (upper left side of all prediction plots).

![grafik](https://user-images.githubusercontent.com/31093529/120279464-c29f7a80-c2b6-11eb-963c-810a13e2a2b1.png)

I have fiddled a bit with the `prob_thresh` parameter of `model.predict_instances` which prevented those false positives in this case, but now some smaller bubbles might not be detected anymore.
Is there another option for handling those kinds of cases?

I have also seen a `train_shape_completion` parameter in the training configuration object but did not really understand what it is used for. Would that be something to try for the problem?

**Comment by maweigert** [comment]
Hi @codingS3b ,

Happy stardist is useful for you! 

First, to see better diagnose these things, I would suggest plottin the center probability map (on which object candidates is based) to see what is going on at the edge:

```python

prob, _  = model.predict(normalize(img))

plt.imshow(prob)

```  

To get rid of the mispredictions you see at the edge you could then try to 

* include more of the border regions in your training set
* pad the image before prediction  - e.g with `np.pad(img, 16, mode="reflect")` - and then cropping it again

Hope this helps, 

Martin

**Comment by maweigert** [comment]
> with "then cropping it again" you mean after prediction on the padded image, right?

Yes. (Sorry, forgot to answer :)
