### ISSUE TITLE
Is there a way to limit the cores dedicated to prediction process?

### ISSUE THREAD

**Issue by pouyadfd** [stardist/stardist#151]
Hi,

First of all thank you for the great job which proved quite accurate in this application! As I noticed for prediction, apart from the first step that can be run on GPU, the second step (postprocessing) would be done on CPU using as many cores as available. I was wondering if there is a way to restrict this behavior since this internally parallelization would slow down other ongoing processing on the machine. I would be so thankful if you consider replying and helping me  with this.

Cheers,

**Comment by uschmidt83** [comment]
Hi @pouyadfd,

I'm glad StarDist is helpful for your application.

> I was wondering if there is a way to restrict this behavior since this internally parallelization would slow down other ongoing processing on the machine.

StarDist's post-processing is using [OpenMP](https://en.wikipedia.org/wiki/OpenMP) for parallelization, which means that you can control the number of threads with the environment variable `OMP_NUM_THREADS`. You can also set this from within Python, e.g. by pasting this at the very top of your script or notebook:

```python
import os
n_threads = 2
os.environ['OMP_NUM_THREADS'] = str(n_threads)
```

**Comment by pouyadfd** [comment]
Hi Uwe,

Thanks a lot!!!
