### ISSUE TITLE
Predicting completed shapes for partially visible cells at the image boundary gives error

### ISSUE THREAD

**Issue by qinghongwan** [stardist/stardist#154]
I run the file named 2_training.ipynb(path"stardist/examples/other2D/2_training.ipynb") to predict completed shapes for partially visible cells at the image boundary.

But I got a error:

With shape completion¶
With shape_completion = True (see Config2D below), the trained StarDist2D model will predict completed shapes for partially visible cells at the image boundary. For this to work, the image needs to be cropped, which is controlled by the Config2D parameter train_completion_crop (default 32), which should be chosen based on the size of the objects. Furthermore, it may be a good idea to increase train_batch_size to offset the reduced amount of pixels per training patch due to cropping.

code: 
np.random.seed(42)
data = StarDistData2D(X,Y,batch_size=1,n_rays=32,patch_size=(256,256),shape_completion=True,length=1)
(img,), (prob,dist) = data[0]

---------------------------------------------------------------------------
UnboundLocalError                         Traceback (most recent call last)
<ipython-input-69-586eb764bf85> in <module>
----> 1 (img,), (prob,dist) = data[0]

~/miniconda3/envs/st2/lib/python3.8/site-packages/stardist/models/model2d.py in __getitem__(self, i)
     71 
     72             dist      = dist[self.ss_grid]
---> 73             dist_mask = np.stack([edt_prob(lbl[self.b][self.ss_grid[1:3]]) for lbl in Y_cleared])
     74         else:
     75             # directly subsample with grid

UnboundLocalError: local variable 'dist' referenced before assignment

Thanks for all your support !!

**Comment by uschmidt83** [comment]
Hi @qinghongwan, thanks for reporting! It's a simple bug that I've [just fixed](https://github.com/stardist/stardist/commit/0993844dba2bfee55b6b14045798d19e4be1519a) in the `dev` branch.

You can install this branch via `pip install git+https://github.com/stardist/stardist@dev` before we make a new proper release (no schedule for that yet). However, you might run into [installation issues](https://github.com/stardist/stardist#installation-1).

**Comment by uschmidt83** [comment]
Hi @qinghongwan, the latest release (0.7.2) fixes this issue and is now on PyPI, i.e. you can install it via `pip install stardist`.
