### ISSUE TITLE
Undefined variable dist

### ISSUE THREAD

**Issue by frycaktadeas** [stardist/stardist#155]
Hello,

I am getting an error `UnboundLocalError: local variable 'dist' referenced before assignment` when I set `shape_completion=True` in my config/StarDistData2D like in this notebook: https://nbviewer.jupyter.org/github/stardist/stardist/blob/master/examples/other2D/2_training.ipynb#With-shape-completion notebook

I think there is a [typo on line 69 in model2d.py](https://github.com/stardist/stardist/blob/master/stardist/models/model2d.py?#L69), because even original notebook without any changes is not working. It is ok when I edit the internal variable name to `dist` without the underscore.

Tadeáš Fryčák

**Comment by uschmidt83** [comment]
Hi @frycaktadeas, you are right about this. This already came up a few days ago (see #154)  and will be fixed in the next release. If you need a fix now, [see this](https://github.com/stardist/stardist/issues/154#issuecomment-885661470).

Best,
Uwe
