### ISSUE TITLE
Exporting Models to Use on Other Platforms

### ISSUE THREAD

**Issue by michaelschwimmer** [stardist/stardist#158]
Hi!

I trained a model on my home graphics card but wanted to do prediction on a work cluster that has my files, so I copied the corresponding model folder from my machine to the cluster, and it doesnt seem to recognise the model. Is this something to do with the logs, as it can tell that the model was trained on a different system? Is there a workaround to this, or a more logica way of exporting models to use cross-platform?

Thanks a lot, and best wishes!

Michael Schwimmer

**Comment by uschmidt83** [comment]
Hi Michael,

> I trained a model on my home graphics card but wanted to do prediction on a work cluster that has my files, so I copied the corresponding model folder from my machine to the cluster, and it doesnt seem to recognise the model.

that should work. Can you be more specific what you did and what the error message was?  
Maybe the version of StarDist on the cluster is much older than on your computer at home?

> Is this something to do with the logs, as it can tell that the model was trained on a different system?

No, the logs aren't relevant for this.

Best,
Uwe
