### ISSUE TITLE
Generalization capabilities of trained models

### ISSUE THREAD

**Issue by anorak94** [stardist/stardist#161]
I am using stardist to segment cells in fluorescence microscopy images. I have images acquired at multiple resolutions going from 2000x2000 px to 11000x11000 px with images having resolution between these two ranges as well. I wanted to know should I be training a different model for each of these resolutions or will having one model suffice. Or should I train a model for each intermediate range. Shouldn't data augmentation take care of these resolution differences. I notice that the performance deteriorates when predicting across different resolution. Also when I try to train the network on all the different resolution images at the same time. The error goes to NaN pretty soon. Can you guys weigh in on this and maybe help me with what the best way to go about such a thing would be. 

Thanks a lot

**Comment by uschmidt83** [comment]
Hi @anorak94, please post your question at the image.sc forum [as instructed when opening a new issue](https://github.com/stardist/stardist/issues/new?assignees=&labels=&template=_1_question-help-support.md&title=). This will greatly increase your chances at receiving a quick and comprehensive answer.

Best,
Uwe
