### ISSUE TITLE
Can't call from_pretrained inside a multiprocessing worker

### ISSUE THREAD

**Issue by kesinger** [stardist/stardist#162]
**Describe the bug**

If  `model = StarDist2D.from_pretrained('2D_versatile_he')` is called from within a  multiprocessing worker started with apply_async,  it freezes at `Found model '2D_versatile_he' for 'StarDist2D'`

**To reproduce**

```python
import multiprocessing as  mp
from stardist.models import StarDist2D
import os
def just_create(queue, outqueue):
    print(f"Creating model in worker {os.getpid()}
    model  = StarDist2D.from_pretrained('2D_versatile_he')
    print("Model creation done")

if __name__=="__main__":
    m = mp.Manager()
    queue = m.Queue()
    outqueue = m.Queue()
    p = mp.Pool(5)
    workers = [p.apply_async(just_create, (queue, outqueue)) for i in range(5)]
    [w.get() for w in workers]
```

**Expected behavior**

I expected `from_pretrained` to have printed lines about 'Loading network weights', 'Loading thresholds', and 'Using default values' as it does in the singlethreaded mode.

**Environment (please complete the following information):**
 - StarDist version 0.7.2
 - CSBDeep version 0.6.3
 - TensorFlow version 2.4.0
 - OS: linux

**Comment by uschmidt83** [comment]
I tried this and can reproduce it *sometimes*, but not always. It seems to be caused by building the Keras/TensorFlow model when the StarDist model is created, hence I'm not sure what I can do about this...

What are you trying to do?

PS: It's not specific to `StarDist2D.from_pretrained('2D_versatile_he')`, e.g. replace it with `StarDist2D(basedir=None)`.

**Comment by kesinger** [comment]
I have a lot of WSI  that I want to run stardist on, and also a lot of spare cpu.   (Going by ps and htop, current inference doesn't seem to be using more than a few cores).

**Comment by uschmidt83** [comment]
StarDist prediction consists of two steps:
1. TensorFlow/Keras model inference, which runs multi-threaded on the CPU or GPU
2. Non-maximum suppression, which runs multi-threaded on the CPU

If you're not seeing any substantial CPU usage, it could either be that your images are small or there aren't many objects in them.

Anyway, I'd recommend to run StarDist prediction in parallel from the command line by launching a prediction script with different arguments (e.g. path to WSI). To that end, you can explicitly control the [threading behavior of TensorFlow](https://www.tensorflow.org/api_docs/python/tf/config/threading) for step 1 (if you don't use a GPU), and also use the enviornment variable `OMP_NUM_THREADS` to control the number of threads used by step 2.
