### ISSUE TITLE
the formula to calculate AP (para.3.2 in the paper)

### ISSUE THREAD

**Issue by captainst** [stardist/stardist#164]
Dear authors,

I have a question retgarding AP formula in para.3.2 of the paper, as AP = TP/(TP+FP+FN). This is quite different from the ordinary AP formula, as the area under the PR curve.

Is there a reference to this average precision calculation? Many thanks.

**Comment by uschmidt83** [comment]
If I remember correctly, we took that terminology from the [2018 Data Science Bowl](https://www.kaggle.com/c/data-science-bowl-2018/overview/evaluation), although they average that metric over several thresholds. 

I think what we used is more commonly known as [Accuracy](https://en.wikipedia.org/wiki/Accuracy_and_precision#In_binary_classification). Note that we ignore TN, as is common in object detection.
(Relevant [code](https://github.com/stardist/stardist/blob/dfa87b7d1e4c431fba0e57d988c93a3b2067cbb4/stardist/matching.py#L93-L103) that computes these metrics.)

Best,
Uwe

**Comment by captainst** [comment]
Hi Uwe,

Thank you for your info. I did not notice the matrics used by kaggle. From you referenced wiki page, I think that the formula in the paper is closer to "Accuracy". In object detection/segmentation, the TN is the background, so I think that it does make sense to use **AP = TP/(TP+FP+FN)** as the Accuracy.

Thank you again !

**Comment by wzr0108** [comment]
how to get AP
