### ISSUE TITLE
Windows 10 - StarDist-V073 - save_weights requires h5py when saving in hdf5

### ISSUE THREAD

**Issue by cberri** [stardist/stardist#166]
Dear All,

I am trying to run stardist_V073 in a jupyter notebook on a local Windows 10 workstation with CUDA 11.0, and TF 2.4.0 but unfortunately I get the following error message:

```
Epoch 1/400
WARNING:tensorflow:AutoGraph could not transform <function _gcd_import at 0x000001F72047E430> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: Unable to locate the source code of <function _gcd_import at 0x000001F72047E430>. Note that functions defined in certain environments, like the interactive Python shell do not expose their source code. If that is the case, you should to define them in a .py source file. If you are certain the code is graph-compatible, wrap the call using @tf.autograph.do_not_convert. Original error: could not get source code
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
WARNING: AutoGraph could not transform <function _gcd_import at 0x000001F72047E430> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: Unable to locate the source code of <function _gcd_import at 0x000001F72047E430>. Note that functions defined in certain environments, like the interactive Python shell do not expose their source code. If that is the case, you should to define them in a .py source file. If you are certain the code is graph-compatible, wrap the call using @tf.autograph.do_not_convert. Original error: could not get source code
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
100/100 [==============================] - 6s 35ms/step - loss: 2.7778 - prob_loss: 0.3665 - dist_loss: 9.0414 - prob_class_loss: 0.6031 - prob_kld: 0.3175 - dist_relevant_mae: 9.0412 - dist_relevant_mse: 121.1503 - dist_dist_iou_metric: 0.0486 - val_loss: 2.0168 - val_prob_loss: 0.2446 - val_dist_loss: 6.4863 - val_prob_class_loss: 0.4749 - val_prob_kld: 0.1732 - val_dist_relevant_mae: 6.4857 - val_dist_relevant_mse: 70.6139 - val_dist_dist_iou_metric: 0.2198

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
C:\Users\CARLOB~1\AppData\Local\Temp/ipykernel_9564/1463295039.py in <module>
     13     model = StarDist2D.from_pretrained("2D_versatile_fluo")
     14 else:
---> 15     model.train(X_trn, Y_trn, classes=C_trn, validation_data=(X_val,Y_val,C_val), augmenter=augmenter)
     16 None;

~\anaconda3\envs\stardist-V073\lib\site-packages\stardist\models\model2d.py in train(self, X, Y, validation_data, classes, augmenter, seed, epochs, steps_per_epoch, workers)
    450 
    451         fit = self.keras_model.fit_generator if IS_TF_1 else self.keras_model.fit
--> 452         history = fit(iter(self.data_train), validation_data=data_val,
    453                       epochs=epochs, steps_per_epoch=steps_per_epoch,
    454                       workers=workers, use_multiprocessing=workers>1,

~\anaconda3\envs\stardist-V073\lib\site-packages\tensorflow\python\keras\engine\training.py in fit(self, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, validation_batch_size, validation_freq, max_queue_size, workers, use_multiprocessing)
   1143           epoch_logs.update(val_logs)
   1144 
-> 1145         callbacks.on_epoch_end(epoch, epoch_logs)
   1146         training_logs = epoch_logs
   1147         if self.stop_training:

~\anaconda3\envs\stardist-V073\lib\site-packages\tensorflow\python\keras\callbacks.py in on_epoch_end(self, epoch, logs)
    426     for callback in self.callbacks:
    427       if getattr(callback, '_supports_tf_logs', False):
--> 428         callback.on_epoch_end(epoch, logs)
    429       else:
    430         if numpy_logs is None:  # Only convert once.

~\anaconda3\envs\stardist-V073\lib\site-packages\tensorflow\python\keras\callbacks.py in on_epoch_end(self, epoch, logs)
   1342     # pylint: disable=protected-access
   1343     if self.save_freq == 'epoch':
-> 1344       self._save_model(epoch=epoch, logs=logs)
   1345 
   1346   def _should_save_on_batch(self, batch):

~\anaconda3\envs\stardist-V073\lib\site-packages\tensorflow\python\keras\callbacks.py in _save_model(self, epoch, logs)
   1391               self.best = current
   1392               if self.save_weights_only:
-> 1393                 self.model.save_weights(
   1394                     filepath, overwrite=True, options=self._options)
   1395               else:

~\anaconda3\envs\stardist-V073\lib\site-packages\tensorflow\python\keras\engine\training.py in save_weights(self, filepath, overwrite, save_format, options)
   2093 
   2094     if save_format == 'h5' and h5py is None:
-> 2095       raise ImportError(
   2096           '`save_weights` requires h5py when saving in hdf5.')
   2097     if save_format == 'tf':

ImportError: `save_weights` requires h5py when saving in hdf5.
```

I tried to reinstall h5py, different versions (above and below 3.0) and change the TF version from 2.4.0 to 2.5.0. Unfortunately I could not solve the problem.

`conda list` return the following: 

```
(stardist-V073) C:\Users\CarloBeretta\Documents\AI\stardist-gpu\notebook_Obj>conda list
# packages in environment at C:\Users\CarloBeretta\anaconda3\envs\stardist-V073:
#
# Name                    Version                   Build  Channel
absl-py                   0.13.0                   pypi_0    pypi
argon2-cffi               20.1.0           py38h2bbff1b_1
astunparse                1.6.3                    pypi_0    pypi
async_generator           1.10               pyhd3eb1b0_0
attrs                     21.2.0             pyhd3eb1b0_0
backcall                  0.2.0              pyhd3eb1b0_0
bleach                    4.0.0              pyhd3eb1b0_0
ca-certificates           2021.7.5             haa95532_1
cachetools                4.2.2                    pypi_0    pypi
certifi                   2021.5.30        py38haa95532_0
cffi                      1.14.6           py38h2bbff1b_0
charset-normalizer        2.0.4                    pypi_0    pypi
colorama                  0.4.4              pyhd3eb1b0_0
csbdeep                   0.6.3                    pypi_0    pypi
cycler                    0.10.0                   pypi_0    pypi
debugpy                   1.4.1            py38hd77b12b_0
decorator                 5.0.9              pyhd3eb1b0_0
defusedxml                0.7.1              pyhd3eb1b0_0
entrypoints               0.3                      py38_0
flatbuffers               1.12                     pypi_0    pypi
gast                      0.3.3                    pypi_0    pypi
google-auth               1.35.0                   pypi_0    pypi
google-auth-oauthlib      0.4.6                    pypi_0    pypi
google-pasta              0.2.0                    pypi_0    pypi
grpcio                    1.32.0                   pypi_0    pypi
h5py                      2.10.0                   pypi_0    pypi
icu                       58.2                 ha925a31_3
idna                      3.2                      pypi_0    pypi
imageio                   2.9.0                    pypi_0    pypi
importlib-metadata        3.10.0           py38haa95532_0
importlib_metadata        3.10.0               hd3eb1b0_0
ipykernel                 6.2.0            py38haa95532_1
ipython                   7.26.0           py38hd4e2768_0
ipython_genutils          0.2.0              pyhd3eb1b0_1
ipywidgets                7.6.3              pyhd3eb1b0_1
jedi                      0.18.0           py38haa95532_1
jinja2                    3.0.1              pyhd3eb1b0_0
jpeg                      9b                   hb83a4c4_2
jsonschema                3.2.0              pyhd3eb1b0_2
jupyter                   1.0.0                    py38_7
jupyter_client            7.0.1              pyhd3eb1b0_0
jupyter_console           6.4.0              pyhd3eb1b0_0
jupyter_core              4.7.1            py38haa95532_0
jupyterlab_pygments       0.1.2                      py_0
jupyterlab_widgets        1.0.0              pyhd3eb1b0_1
keras-preprocessing       1.1.2                    pypi_0    pypi
kiwisolver                1.3.2                    pypi_0    pypi
libpng                    1.6.37               h2a8f88b_0
llvmlite                  0.37.0                   pypi_0    pypi
m2w64-gcc-libgfortran     5.3.0                         6
m2w64-gcc-libs            5.3.0                         7
m2w64-gcc-libs-core       5.3.0                         7
m2w64-gmp                 6.1.0                         2
m2w64-libwinpthread-git   5.0.0.4634.697f757               2
markdown                  3.3.4                    pypi_0    pypi
markupsafe                2.0.1            py38h2bbff1b_0
matplotlib                3.4.3                    pypi_0    pypi
matplotlib-inline         0.1.2              pyhd3eb1b0_2
mistune                   0.8.4           py38he774522_1000
msys2-conda-epoch         20160418                      1
nbclient                  0.5.3              pyhd3eb1b0_0
nbconvert                 6.1.0            py38haa95532_0
nbformat                  5.1.3              pyhd3eb1b0_0
nest-asyncio              1.5.1              pyhd3eb1b0_0
networkx                  2.6.3                    pypi_0    pypi
notebook                  6.4.3            py38haa95532_0
numba                     0.54.0                   pypi_0    pypi
numpy                     1.19.5                   pypi_0    pypi
oauthlib                  3.1.1                    pypi_0    pypi
openssl                   1.1.1l               h2bbff1b_0
opt-einsum                3.3.0                    pypi_0    pypi
packaging                 21.0               pyhd3eb1b0_0
pandocfilters             1.4.3            py38haa95532_1
parso                     0.8.2              pyhd3eb1b0_0
pickleshare               0.7.5           pyhd3eb1b0_1003
pillow                    8.3.2                    pypi_0    pypi
pip                       21.2.2           py38haa95532_0
prometheus_client         0.11.0             pyhd3eb1b0_0
prompt-toolkit            3.0.17             pyhca03da5_0
prompt_toolkit            3.0.17               hd3eb1b0_0
protobuf                  3.17.3                   pypi_0    pypi
pyasn1                    0.4.8                    pypi_0    pypi
pyasn1-modules            0.2.8                    pypi_0    pypi
pycparser                 2.20                       py_2
pygments                  2.10.0             pyhd3eb1b0_0
pyparsing                 2.4.7              pyhd3eb1b0_0
pyqt                      5.9.2            py38ha925a31_4
pyrsistent                0.17.3           py38he774522_0
python                    3.8.0                hff0d562_2
python-dateutil           2.8.2              pyhd3eb1b0_0
pywavelets                1.1.1                    pypi_0    pypi
pywin32                   228              py38hbaba5e8_1
pywinpty                  0.5.7                    py38_0
pyzmq                     22.2.1           py38hd77b12b_1
qt                        5.9.7            vc14h73c81de_0
qtconsole                 5.1.0              pyhd3eb1b0_0
qtpy                      1.10.0             pyhd3eb1b0_0
requests                  2.26.0                   pypi_0    pypi
requests-oauthlib         1.3.0                    pypi_0    pypi
rsa                       4.7.2                    pypi_0    pypi
scikit-image              0.18.3                   pypi_0    pypi
scipy                     1.7.1                    pypi_0    pypi
send2trash                1.5.0              pyhd3eb1b0_1
setuptools                52.0.0           py38haa95532_0
sip                       4.19.13          py38ha925a31_0
six                       1.15.0                   pypi_0    pypi
sqlite                    3.36.0               h2bbff1b_0
stardist                  0.7.3                    pypi_0    pypi
tensorboard               2.6.0                    pypi_0    pypi
tensorboard-data-server   0.6.1                    pypi_0    pypi
tensorboard-plugin-wit    1.8.0                    pypi_0    pypi
tensorflow-estimator      2.4.0                    pypi_0    pypi
tensorflow-gpu            2.4.0                    pypi_0    pypi
termcolor                 1.1.0                    pypi_0    pypi
terminado                 0.9.4            py38haa95532_0
testpath                  0.5.0              pyhd3eb1b0_0
tifffile                  2021.8.30                pypi_0    pypi
tornado                   6.1              py38h2bbff1b_0
tqdm                      4.62.2                   pypi_0    pypi
traitlets                 5.0.5              pyhd3eb1b0_0
typing-extensions         3.7.4.3                  pypi_0    pypi
urllib3                   1.26.6                   pypi_0    pypi
vc                        14.2                 h21ff451_1
vs2015_runtime            14.27.29016          h5e58377_2
wcwidth                   0.2.5              pyhd3eb1b0_0
webencodings              0.5.1                    py38_1
werkzeug                  2.0.1                    pypi_0    pypi
wheel                     0.37.0             pyhd3eb1b0_1
widgetsnbextension        3.5.1                    py38_0
wincertstore              0.2                      py38_0
winpty                    0.4.3                         4
wrapt                     1.12.1                   pypi_0    pypi
zipp                      3.5.0              pyhd3eb1b0_0
zlib                      1.2.11               h62dcd97_4
```

Do you have any suggestion how to solve this issue?

Please let me know if you need any further information.

Thank you for your help.

Carlo

**Comment by maweigert** [comment]
Could you post the output of the following:

1. 
```python
import h5py
print(h5py.__version__)
```

2.
```python
from tensorflow.python.keras.engine.training import h5py
print(h5py)
```

**Comment by cberri** [comment]
Dear Martin,

Thank you for your quick reply. Below the output of the two commands:

```python
>>> import h5py
>>> print(h5py.__version__)
2.10.0
>>> from tensorflow.python.keras.engine.training import h5py
2021-09-13 18:26:47.320018: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudart64_110.dll
>>> print(h5py)
<module 'h5py' from 'C:\\Users\\CarloBeretta\\anaconda3\\envs\\stardist-V073\\lib\\site-packages\\h5py\\__init__.py'>
```

**Comment by maweigert** [comment]
Ok, could you try:

```python

import tensorflow as tf

inp = tf.keras.layers.Input((None,None, 1))
out = tf.keras.layers.Conv2D(1, 1)(inp)
model = tf.keras.models.Model(inp, out)

model.save_weights('foo.h5')
```

**Comment by cberri** [comment]
Here is the output:

(stardist-V073) C:\Users\CarloBeretta\Documents\AI\stardist-gpu\notebook_Obj>python
Python 3.8.0 (default, Nov  6 2019, 16:00:02) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.

>>> import tensorflow as tf
>>> 2021-09-13 22:18:03.838154: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudart64_110.dll
>>> inp = tf.keras.layers.Input((None,None, 1))
>>> out = tf.keras.layers.Conv2D(1, 1)(inp)
>>> 2021-09-13 22:18:15.748346: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
>>> 2021-09-13 22:18:15.749242: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library nvcuda.dll
>>> 2021-09-13 22:18:15.774063: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1720] Found device 0 with properties:
>>> pciBusID: 0000:68:00.0 name: NVIDIA GeForce RTX 3080 computeCapability: 8.6
>>> coreClock: 1.785GHz coreCount: 68 deviceMemorySize: 10.00GiB deviceMemoryBandwidth: 707.88GiB/s
>>> 2021-09-13 22:18:15.774185: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudart64_110.dll
>>> 2021-09-13 22:18:15.799537: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cublas64_11.dll
>>> 2021-09-13 22:18:15.799657: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cublasLt64_11.dll
>>> 2021-09-13 22:18:15.813943: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cufft64_10.dll
>>> 2021-09-13 22:18:15.817000: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library curand64_10.dll
>>> 2021-09-13 22:18:15.856761: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cusolver64_10.dll
>>> 2021-09-13 22:18:15.869292: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cusparse64_11.dll
>>> 2021-09-13 22:18:15.869941: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudnn64_8.dll
>>> 2021-09-13 22:18:15.870049: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1862] Adding visible gpu devices: 0
>>> 2021-09-13 22:18:15.870619: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2
>>> To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
>>> 2021-09-13 22:18:15.871612: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1720] Found device 0 with properties:
>>> pciBusID: 0000:68:00.0 name: NVIDIA GeForce RTX 3080 computeCapability: 8.6
>>> coreClock: 1.785GHz coreCount: 68 deviceMemorySize: 10.00GiB deviceMemoryBandwidth: 707.88GiB/s
>>> 2021-09-13 22:18:15.871707: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudart64_110.dll
>>> 2021-09-13 22:18:15.872032: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cublas64_11.dll
>>> 2021-09-13 22:18:15.872403: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cublasLt64_11.dll
>>> 2021-09-13 22:18:15.872728: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cufft64_10.dll
>>> 2021-09-13 22:18:15.873015: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library curand64_10.dll
>>> 2021-09-13 22:18:15.873339: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cusolver64_10.dll
>>> 2021-09-13 22:18:15.873635: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cusparse64_11.dll
>>> 2021-09-13 22:18:15.873900: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudnn64_8.dll
>>> 2021-09-13 22:18:15.874251: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1862] Adding visible gpu devices: 0
>>> 2021-09-13 22:18:16.315793: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1261] Device interconnect StreamExecutor with strength 1 edge matrix:
>>> 2021-09-13 22:18:16.315896: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1267]      0
>>> 2021-09-13 22:18:16.317457: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1280] 0:   N
>>> 2021-09-13 22:18:16.317936: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1406] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 8444 MB memory) -> physical GPU (device: 0, name: NVIDIA GeForce RTX 3080, pci bus id: 0000:68:00.0, compute capability: 8.6)
>>> 2021-09-13 22:18:16.318705: I tensorflow/compiler/jit/xla_gpu_device.cc:99] Not creating XLA devices, tf_xla_enable_xla_devices not set
>>> model = tf.keras.models.Model(inp, out)
>>> model.save_weights('foo.h5')

**Comment by maweigert** [comment]
ok, thats weird then. Could you just restart the original training notebook and try again?

**Comment by cberri** [comment]
Unfortunately, I get the same error message. I can try to run the same notebook under Ubuntu 18.4 and see if the issue is just Windows 10 related!

**Comment by cberri** [comment]
On Ubuntu 18.4 the training runs without any problem. Just some CUBLAS problem but I guess for memory reason.

`2021-09-14 19:07:45.714227: E tensorflow/stream_executor/cuda/cuda_blas.cc:226] failed to create cublas handle: CUBLAS_STATUS_NOT_INITIALIZED`

Do you have any additional suggestion/magic for Windows 10?

Thank you!

**Comment by maweigert** [comment]
Mhm, maybe one last try reinstalling `h5py`:

```
conda uninstall h5py
pip install h5py==2.10.0
```

**Comment by cberri** [comment]
Unfortunately the magic didn't help:

(base) C:\Users\CarloBeretta>conda activate stardist-V073

(stardist-V073) C:\Users\CarloBeretta>conda uninstall h5py
Collecting package metadata (repodata.json): done
Solving environment: failed

PackagesNotFoundError: The following packages are missing from the target environment:
  - h5py

(stardist-V073) C:\Users\CarloBeretta>pip install h5py==2.10.0
Requirement already satisfied: h5py==2.10.0 in c:\users\carloberetta\anaconda3\envs\stardist-v073\lib\site-packages (2.10.0)
Requirement already satisfied: six in c:\users\carloberetta\anaconda3\envs\stardist-v073\lib\site-packages (from h5py==2.10.0) (1.16.0)
Requirement already satisfied: numpy>=1.7 in c:\users\carloberetta\anaconda3\envs\stardist-v073\lib\site-packages (from h5py==2.10.0) (1.19.5)

**Comment by cberri** [comment]
I also tried the following but without any success:

(stardist-V073) C:\Users\CarloBeretta>conda install h5py==2.10.0
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: C:\Users\CarloBeretta\anaconda3\envs\stardist-V073

  added / updated specs:
    - h5py==2.10.0


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    h5py-2.10.0                |   py38h5e291fa_0         841 KB
    hdf5-1.10.4                |       h7ebc959_0         7.9 MB
    ------------------------------------------------------------
                                           Total:         8.8 MB

The following NEW packages will be INSTALLED:

  blas               pkgs/main/win-64::blas-1.0-mkl
  h5py               pkgs/main/win-64::h5py-2.10.0-py38h5e291fa_0
  hdf5               pkgs/main/win-64::hdf5-1.10.4-h7ebc959_0
  icc_rt             pkgs/main/win-64::icc_rt-2019.0.0-h0cc432a_1
  intel-openmp       pkgs/main/win-64::intel-openmp-2021.3.0-haa95532_3372
  mkl                pkgs/main/win-64::mkl-2021.3.0-haa95532_524
  mkl-service        pkgs/main/win-64::mkl-service-2.4.0-py38h2bbff1b_0
  mkl_fft            pkgs/main/win-64::mkl_fft-1.3.0-py38h277e83a_2
  mkl_random         pkgs/main/win-64::mkl_random-1.2.2-py38hf11a4ad_0
  numpy              pkgs/main/win-64::numpy-1.20.3-py38ha4e8547_0
  numpy-base         pkgs/main/win-64::numpy-base-1.20.3-py38hc2deb75_0
  pyreadline         pkgs/main/win-64::pyreadline-2.1-py38_1


Proceed ([y]/n)? y


Downloading and Extracting Packages
hdf5-1.10.4          | 7.9 MB    | ############################################################################ | 100%
h5py-2.10.0          | 841 KB    | ############################################################################ | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: done

**Comment by maweigert** [comment]
ok, thats weird. Did the error persist?
