### ISSUE TITLE
model.predict crashes on colab for 3D data

### ISSUE THREAD

**Issue by kapoorlab** [stardist/stardist#167]
Hi, Thank you for making stardist 3D, which is very useful for object detection. I am running into an issue while using model.predict in Colab on an image of size (32,1024,1024) and even with tiling (8,8,8) I could not get model.predict to run on Colab Pro+ with 51GB of GPU RAM, which is strange because it seems huge enough RAM for the prediction to work. Is there a way to use the model.predict function in a computationally less intensive way?

Many thanks for your help.

**Comment by uschmidt83** [comment]
Hi @kapoorlab, as [mentioned in our issue templates](https://github.com/stardist/stardist/issues/new/choose), please make a new post on the image.sc forum to discuss general questions like this.
