### ISSUE TITLE
255 labels

### ISSUE THREAD

**Issue by usmanqureshi94** [stardist/stardist#168]
What if I have more than 255 labels in an image how can I label all of them distinctly  ?

**Comment by maweigert** [comment]
`If you open a new topic, please provide a clear and concise description to understand and ideally reproduce the issue you're having`

**Comment by usmanqureshi94** [comment]
I've an image with about 500 artifacts which I want to annotate programmatically through a baseline model. A Subject matter expert will load them into imageJ to remove false positive. Since there are more than 255 artifacts I was just wondering how can I assign them different labels in a binary image. If SME has to remove label 255 all other polygons with intensity 255 will be removed.


![image](https://user-images.githubusercontent.com/82107583/134019443-2401c7a3-160f-4bb8-a54f-8c104b6ea313.png)

**Comment by maweigert** [comment]
Hi, 
I still don't understand the nature of your problem. Is it about converting a binary image into a label image? 
Any case, this seems more like a question for the [image.sc](https://forum.image.sc/) forum.

**Comment by saskra** [comment]
I suppose the problem is that some software can only process 8 bit images, which is why you are limited to a maximum of 255 labels plus background with these. So if possible, you should work with 16 bit (65,536 colours).
