### ISSUE TITLE
libstardist3D C++ implementation for 3D prediction?

### ISSUE THREAD

**Issue by tractatus** [stardist/stardist#169]
I was wondering if there is a minimal working example on running prediction of StarDist3D directly from C++? Using `libstardist3d`?
https://github.com/stardist/stardist/tree/master/stardist/lib

The Fiji plugin seems only to support 2D. 

Pete Bankhead made a nice Java implementation using OpenCV DNN (https://github.com/qupath/qupath-extension-stardist) by converting the keras model to a frozen OpenCV DNN acceptable `.pb` format using:
```
python -m tf2onnx.convert --opset 10 --saved-model "/path/to/saved/model/directory" --output_frozen_graph "/path/to/output/model/file.pb"
```
Unfortunately, OpenCV DNN at the moment has very poor support for `conv3d` and similar 3D operations. From what I can see there is also very little intention of supporting 3D for OpenCV DNN in the near future.

Anyone tried TensorRT or OpenVINO for this?

**Comment by uschmidt83** [comment]
Please keep the discussion at one place, i.e. where you [originally asked this question in the forum](https://forum.image.sc/t/libstardist3d-c-implementation-for-3d-prediction/58133).
