### ISSUE TITLE
Train stardist using ImageDataGenerator

### ISSUE THREAD

**Issue by LuisFMCuriel** [stardist/stardist#172]
Hi!
First of all, thank you so much for this tool. I think we all agree that this network has been the standard tool for cell segmentation. I was wondering if there is an easy way to train the network using an **ImageDataGenerator**. I have my dataset stored in this format (to make easier the training of NN, save some memory, and apply data augmentation), but I am not sure how to train this network with my data. I was trying something like:

```
batch_train = 32
batch_evaluate = 8
image_generator_training = image_datagen.flow(np.array((imgs), dtype="float32"), batch_size =batch_train, seed = seed, shuffle = False, subset="training")
mask_generator_training = mask_datagen.flow(np.array((masks), dtype="float32"), batch_size = batch_train, seed = seed, shuffle = False, subset="training")
train_generator = zip(image_generator_training, mask_generator_training)

image_generator_validation = image_datagen.flow(np.array((imgs), dtype="float32"), batch_size =batch_evaluate, seed = seed, shuffle = False, subset="validation")
mask_generator_validation = mask_datagen.flow(np.array((masks), dtype="float32"), batch_size = batch_evaluate, seed = seed, shuffle = False, subset="validation")
validation_generator = zip(image_generator_validation, mask_generator_validation)
```
Afterwards, typically I use `model.fit(train_generator, validation_data=validation_generator, epochs=*)` to train using my generator, but of course, this does not work with this model (using your train function). I would like to perform transfer learning using your model **_'2D_versatile_fluo'_**. Any idea how I can do this?

I really appreciate your time.
Thanks!!

**Comment by uschmidt83** [comment]
> I was wondering if there is an easy way to train the network using an **ImageDataGenerator**.

You could use a `Sequence` to do that, e.g. see https://github.com/stardist/stardist/issues/107.

> I would like to perform transfer learning using your model **_'2D_versatile_fluo'_**. Any idea how I can do this?

This is how you can duplicate a pretrained model and prepare it for transfer learning:

```python
# imports
from stardist.models import StarDist2D, keras_import
import shutil
from pathlib import Path
keras = keras_import()

# name of your model
my_name = '2D_versatile_fluo_FINETUNED'

# load pretrained model and make a copy to local folder
model_pretrained = StarDist2D.from_pretrained('2D_versatile_fluo')
if not Path(my_name).exists():
    shutil.copytree(model_pretrained.logdir, my_name)

# load your duplicate of the pretrained model
my_model = StarDist2D(None, my_name)

# change optimizer, especially to use smaller learning rate for finetuning
# (e.g. 1e-5, you have to try what works best)
my_model.prepare_for_training(keras.optimizers.Adam(1e-5))

# finetune model with your data...
# my_model.train(...)
```
