### ISSUE TITLE
example of training MoNuSeg2018 dataset?

### ISSUE THREAD

**Issue by zhangliukun** [stardist/stardist#176]
In the example 2_train.py, the dsb2018 dataset is used. I would like to train the 2D_versatile_he model. how could I find some examples?

**Comment by maweigert** [comment]
Hi, 

we used the publically datset from the monuseg challenge, which can be found here:

https://monuseg.grand-challenge.org/Data/

Note that (as far as I remember) the format for the ground truth masks is a bit different there, so you most likely would need to bring it into the form stardist expects (i.e. label integer images). 
Hope that helps.
