### ISSUE TITLE
Update Labkit labeling instructions

### ISSUE THREAD

**Issue by Theresa-S** [stardist/stardist#185]
Dear developers,

I'm currently labeling cells for training our own StarDist model and I'm using Labkit for that task. I followed the instructions from your readme, but after some images I noticed that the checked box has changed its function (and, to be fair, its name:-)
When exporting the images, "allow overlapping labels" leads to three annotated objects instead of two (lefthand), whereas an unchecked box leads to the correct two annotated cells (righthand)

![grafik](https://user-images.githubusercontent.com/61883896/156743539-428202cb-bdf2-45a9-bdce-4b8273c1fe7d.png)

On another note, do I need the ".labels" file that is created alongside the ".tif" images during export? :-)

**Comment by uschmidt83** [comment]
Dear @Theresa-S, thank you very much for lettings us know and I apologize for the *very* late reply!
I've just updated [our README](https://github.com/stardist/stardist/tree/4116fc9bb5cd0b0c2486a242abccc3d746d2a8b9#annotating-with-labkit-2d-or-3d) accordingly.

Thanks,
Uwe
