### ISSUE TITLE
Threshold optimization step in 2D pipeline after training error

### ISSUE THREAD

**Issue by Nal44** [stardist/stardist#190]
Hi all stardist community,

I am running into an issue after training a 2D pipeline. I am using stardist 0.8.0 all the steps goes well up to training and after training at the Threshold optimization step I get an error (see below): 

The model is trained, and the predictions seems pretty good but I can get the optimization nor the performances graphs ...

it gives me another error ( see below).

Could you help to point out where the errors comes from and how to fix it ?

Thanks a lot,
antho

PS: if needed I can post the whole notebook , perhaps I made a mistake somewhere since I changed a few things from your original one .

ERROR 1 :

Threshold optimization

While the default values for the probability and non-maximum suppression thresholds already yield good results in many cases, we still recommend to adapt the thresholds to your data. The optimized threshold values are saved to disk and will be automatically loaded with the model.

1
if quick_demo:
2
    model.optimize_thresholds(X_val[:2], Y_val[:2])
3
else:
4
    model.optimize_thresholds(X_val, Y_val)
NMS threshold = 0.3:   0%|          | 0/20 [00:08<?, ?it/s]
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-18-bf85bc6d42ab> in <module>
      2     model.optimize_thresholds(X_val[:2], Y_val[:2])
      3 else:
----> 4     model.optimize_thresholds(X_val, Y_val)

/opt/anaconda3/lib/python3.8/site-packages/stardist/models/base.py in optimize_thresholds(self, X_val, Y_val, nms_threshs, iou_threshs, predict_kwargs, optimize_kwargs, save_to_json)
    968         opt_prob_thresh, opt_measure, opt_nms_thresh = None, -np.inf, None
    969         for _opt_nms_thresh in nms_threshs:
--> 970             _opt_prob_thresh, _opt_measure = optimize_threshold(Y_val, Yhat_val, model=self, nms_thresh=_opt_nms_thresh, iou_threshs=iou_threshs, **optimize_kwargs)
    971             if _opt_measure > opt_measure:
    972                 opt_prob_thresh, opt_measure, opt_nms_thresh = _opt_prob_thresh, _opt_measure, _opt_nms_thresh

/opt/anaconda3/lib/python3.8/site-packages/stardist/utils.py in optimize_threshold(Y, Yhat, model, nms_thresh, measure, iou_threshs, bracket, tol, maxiter, verbose)
    302             return -value
    303 
--> 304         opt = minimize_scalar(fn, method='golden', bracket=bracket, tol=tol, options={'maxiter': maxiter})
    305 
    306     verbose > 1 and print('\n',opt, flush=True)

/opt/anaconda3/lib/python3.8/site-packages/scipy/optimize/_minimize.py in minimize_scalar(fun, bracket, bounds, args, method, tol, options)
    800         return _minimize_scalar_bounded(fun, bounds, args, **options)
    801     elif meth == 'golden':
--> 802         return _minimize_scalar_golden(fun, bracket, args, **options)
    803     else:
    804         raise ValueError('Unknown solver %s' % method)

/opt/anaconda3/lib/python3.8/site-packages/scipy/optimize/optimize.py in _minimize_scalar_golden(func, brack, args, xtol, maxiter, **unknown_options)
   2420         xa, xb, xc, fa, fb, fc, funcalls = bracket(func, args=args)
   2421     elif len(brack) == 2:
-> 2422         xa, xb, xc, fa, fb, fc, funcalls = bracket(func, xa=brack[0],
   2423                                                    xb=brack[1], args=args)
   2424     elif len(brack) == 3:

/opt/anaconda3/lib/python3.8/site-packages/scipy/optimize/optimize.py in bracket(func, xa, xb, args, grow_limit, maxiter)
   2536     _gold = 1.618034  # golden ratio: (1.0+sqrt(5.0))/2.0
   2537     _verysmall_num = 1e-21
-> 2538     fa = func(*(xa,) + args)
   2539     fb = func(*(xb,) + args)
   2540     if (fa < fb):                      # Switch so fa > fb

/opt/anaconda3/lib/python3.8/site-packages/stardist/utils.py in fn(thr)
    287             if value is None:
    288                 Y_instances = [model._instances_from_prediction(y.shape, *prob_dist, prob_thresh=prob_thresh, nms_thresh=nms_thresh)[0] for y,prob_dist in zip(Y,Yhat)]
--> 289                 stats = matching_dataset(Y, Y_instances, thresh=iou_threshs, show_progress=False, parallel=True)
    290                 values[prob_thresh] = value = np.mean([s._asdict()[measure] for s in stats])
    291             if verbose > 1:

/opt/anaconda3/lib/python3.8/site-packages/stardist/matching.py in matching_dataset(y_true, y_pred, thresh, criterion, by_image, show_progress, parallel)
    236     """
    237     len(y_true) == len(y_pred) or _raise(ValueError("y_true and y_pred must have the same length."))
--> 238     return matching_dataset_lazy (
    239         tuple(zip(y_true,y_pred)), thresh=thresh, criterion=criterion, by_image=by_image, show_progress=show_progress, parallel=parallel,
    240     )

/opt/anaconda3/lib/python3.8/site-packages/stardist/matching.py in matching_dataset_lazy(y_gen, thresh, criterion, by_image, show_progress, parallel)
    261         fn = lambda pair: matching(*pair, thresh=thresh, criterion=criterion, report_matches=False)
    262         with ThreadPoolExecutor() as pool:
--> 263             stats_all = tuple(pool.map(fn, tqdm(y_gen,**tqdm_kwargs)))
    264     else:
    265         stats_all = tuple (

/opt/anaconda3/lib/python3.8/concurrent/futures/_base.py in result_iterator()
    609                     # Careful not to keep a reference to the popped future
    610                     if timeout is None:
--> 611                         yield fs.pop().result()
    612                     else:
    613                         yield fs.pop().result(end_time - time.monotonic())

/opt/anaconda3/lib/python3.8/concurrent/futures/_base.py in result(self, timeout)
    437                 raise CancelledError()
    438             elif self._state == FINISHED:
--> 439                 return self.__get_result()
    440             else:
    441                 raise TimeoutError()

/opt/anaconda3/lib/python3.8/concurrent/futures/_base.py in __get_result(self)
    386     def __get_result(self):
    387         if self._exception:
--> 388             raise self._exception
    389         else:
    390             return self._result

/opt/anaconda3/lib/python3.8/concurrent/futures/thread.py in run(self)
     55 
     56         try:
---> 57             result = self.fn(*self.args, **self.kwargs)
     58         except BaseException as exc:
     59             self.future.set_exception(exc)

/opt/anaconda3/lib/python3.8/site-packages/stardist/matching.py in <lambda>(pair)
    259     if parallel:
    260         from concurrent.futures import ThreadPoolExecutor
--> 261         fn = lambda pair: matching(*pair, thresh=thresh, criterion=criterion, report_matches=False)
    262         with ThreadPoolExecutor() as pool:
    263             stats_all = tuple(pool.map(fn, tqdm(y_gen,**tqdm_kwargs)))

/opt/anaconda3/lib/python3.8/site-packages/stardist/matching.py in matching(y_true, y_pred, thresh, criterion, report_matches)
    161     y_pred, _, map_rev_pred = relabel_sequential(y_pred)
    162 
--> 163     overlap = label_overlap(y_true, y_pred, check=False)
    164     scores = matching_criteria[criterion](overlap)
    165     assert 0 <= np.min(scores) <= np.max(scores) <= 1

/opt/anaconda3/lib/python3.8/site-packages/stardist/matching.py in label_overlap(x, y, check)
     41         _check_label_array(y,'y',True)
     42         x.shape == y.shape or _raise(ValueError("x and y must have the same shape"))
---> 43     return _label_overlap(x, y)
     44 
     45 @jit(nopython=True)

TypeError: expected dtype object, got 'numpy.dtype[uint64]'

ERROR2 (performance step):
Choose several IoU thresholds  𝜏  that might be of interest and for each compute matching statistics for the validation data.

1
taus = [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]
2
stats = [matching_dataset(Y_val, Y_val_pred, thresh=t, show_progress=False) for t in tqdm(taus)]
  0%|          | 0/9 [00:00<?, ?it/s]
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-21-9fc024edc868> in <module>
      1 taus = [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]
----> 2 stats = [matching_dataset(Y_val, Y_val_pred, thresh=t, show_progress=False) for t in tqdm(taus)]

<ipython-input-21-9fc024edc868> in <listcomp>(.0)
      1 taus = [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]
----> 2 stats = [matching_dataset(Y_val, Y_val_pred, thresh=t, show_progress=False) for t in tqdm(taus)]

/opt/anaconda3/lib/python3.8/site-packages/stardist/matching.py in matching_dataset(y_true, y_pred, thresh, criterion, by_image, show_progress, parallel)
    236     """
    237     len(y_true) == len(y_pred) or _raise(ValueError("y_true and y_pred must have the same length."))
--> 238     return matching_dataset_lazy (
    239         tuple(zip(y_true,y_pred)), thresh=thresh, criterion=criterion, by_image=by_image, show_progress=show_progress, parallel=parallel,
    240     )

/opt/anaconda3/lib/python3.8/site-packages/stardist/matching.py in matching_dataset_lazy(y_gen, thresh, criterion, by_image, show_progress, parallel)
    263             stats_all = tuple(pool.map(fn, tqdm(y_gen,**tqdm_kwargs)))
    264     else:
--> 265         stats_all = tuple (
    266             matching(y_t, y_p, thresh=thresh, criterion=criterion, report_matches=False)
    267             for y_t,y_p in tqdm(y_gen,**tqdm_kwargs)

/opt/anaconda3/lib/python3.8/site-packages/stardist/matching.py in <genexpr>(.0)
    264     else:
    265         stats_all = tuple (
--> 266             matching(y_t, y_p, thresh=thresh, criterion=criterion, report_matches=False)
    267             for y_t,y_p in tqdm(y_gen,**tqdm_kwargs)
    268         )

/opt/anaconda3/lib/python3.8/site-packages/stardist/matching.py in matching(y_true, y_pred, thresh, criterion, report_matches)
    161     y_pred, _, map_rev_pred = relabel_sequential(y_pred)
    162 
--> 163     overlap = label_overlap(y_true, y_pred, check=False)
    164     scores = matching_criteria[criterion](overlap)
    165     assert 0 <= np.min(scores) <= np.max(scores) <= 1

/opt/anaconda3/lib/python3.8/site-packages/stardist/matching.py in label_overlap(x, y, check)
     41         _check_label_array(y,'y',True)
     42         x.shape == y.shape or _raise(ValueError("x and y must have the same shape"))
---> 43     return _label_overlap(x, y)
     44 
     45 @jit(nopython=True)

TypeError: expected dtype object, got 'numpy.dtype[uint64]'

Example: Print all available matching statistics for 𝜏=0.5

**Comment by Nal44** [comment]
See the whole notebook attached.
Thanks
antho


[training 2D all.zip](https://github.com/stardist/stardist/files/8465176/training.2D.all.zip)

**Comment by Nal44** [comment]
Prediction examples from this model:

In the liver sections there are some huge detection in the background (Liver section ), could that come from the missing threshold step?
Or something else ?
Did you have this type of detections before ? 

On the other hand the nucleus segmentation is pretty good (just looking by eye ) since I don't have the performance graphs ...

Here : top brain, bottom liver.

Thanks a lot,
antho

![2dmodelantho](https://user-images.githubusercontent.com/64991735/162768617-5b2e2480-ae86-4e58-8b07-d2f824e97ad5.png)

**Comment by Nal44** [comment]
I installed the 0.8.2 and it is fixed :) 

But would still like a heads up on the detections if possible,
thanks

**Comment by maweigert** [comment]
What data was this trained on? (the data in the notebook you shared above seems to be the dsb2018 demo data)

**Comment by Nal44** [comment]
Yes, in part I used dsb2018 and added my own images painted manually (brain liver and lungs) and another dataset : Biostudies dataset S-BSST265.
I wanted to get as much variability as possible in terms on cells shapes, sizes and magnifications.

**Comment by maweigert** [comment]
The dataset that you trained on contains many very large nuclei, so if that is not the case for your liver dataset then this would be suboptimal. If the pretrained model does not work well for you I would suggest annotating some (~20) crops of your liver dataset yourself and retrain.

**Comment by Nal44** [comment]
Thanks,
Well I retrained my model using the threshold optimization and it improved massively (only 1 or 2 big detections from the background) , an only in a few images tested.

I will make some crops and try just to see if it gets better,

thanks !
antho

**Comment by Nal44** [comment]
I installed numba 0.53 version, that fixed the issue.

Antho
