### ISSUE TITLE
StarDist beyond bioimaging

### ISSUE THREAD

**Issue by hijizhou** [stardist/stardist#193]
Hi StarDist community,

This is not an issue, just wound like to share with you one more application that StarDist did a great job.

![Particle identification for battery particles](https://github.com/YijinLiu-Lab/ParticleNetworkDynamics/raw/main/images/particles.png)

This is an image of battery particles from a composite cathode captured by nano-resolution X-ray phase contrast tomography. Though it is not a bioimaging data, with a small adaption, StarDist network works pretty well. See the [published paper](https://www.science.org/doi/10.1126/science.abm8962) for more examples.

Thank you everyone for sharing, maintaining and improving StarDist. The ImageJ plugin that is able to load the pretrained model is also awesome!

Best,
(please feel free to close it)

**Comment by uschmidt83** [comment]
Thank you very much for telling us about your application, it is highly appreciated!
We're glad that StarDist has been useful for your project.

Sorry for the late reply,
Uwe
