### ISSUE TITLE
retrain model with curated images advice ?

### ISSUE THREAD

**Issue by Nal44** [stardist/stardist#196]
Hi,

I have a model trained that works nicely, but there are obviously some mistakes.
Hence I have cured the inferences manually using labkit and now I want to retrain the model with the cured images (images not used for training only new ones and new predictions).

So the question is : 
Should I retrain the whole set of images (training+curated ones) ?
OR only used the model and retrain with the curated ones only without the training set ?

What strategy will work best according to you ?

Thanks a lot,
antho

**Comment by uschmidt83** [comment]
Sorry for the late reply. My short answer is that you have to try it out.
Also, please ask general question like this in the image.sc forum ([as instructed when opening an issue](https://github.com/stardist/stardist/issues/new?assignees=&labels=&template=_1_question-help-support.md&title=)).
