### ISSUE TITLE
Questions about the training data set

### ISSUE THREAD

**Issue by maxi2015qwe** [stardist/stardist#197]
The input data needed for this model training should be the original image and the Masks of the corresponding image.

But I only have the original image and the Lable for the images

How can I input the Label information into the model for training? or do i have to convert the Label to the masks?

Thank you

**Comment by uschmidt83** [comment]
Hi, please read the instructions when opening a [Question/Help/Support issue](https://github.com/stardist/stardist/issues/new?assignees=&labels=&template=_1_question-help-support.md&title=).
