### ISSUE TITLE
Different results from Python Stardist and FIJI

### ISSUE THREAD

**Issue by lambda-science** [stardist/stardist#202]
Hello,

From the FAQ it is written:

> Are there differences between the Python and Fiji versions? Regarding the prediction results of the neural network, they should be identical or only have negligible differences.   

However when using StarDist with Python I get poor results, but using StarDist with FIJI results are great.
See the attached image for the results comparaison of StarDist using Python and using the FIJI implementation on the same image.
Could anyone give me hint on why the segmentation is so different ? Both were done using default parameters.
Here is FIJI Stardist segementation of my image:
![image](https://user-images.githubusercontent.com/20109584/173310032-9ed56ed4-c341-48ee-bf22-deba3b475b92.png)
Here is Python Stardist segementation of my image:
![image](https://user-images.githubusercontent.com/20109584/173310060-d81a805e-ec66-4f79-9978-cea14fbcff66.png)

Here is a link to my raw image: https://i.imgur.com/GBfJ2cn.jpeg
Here is my python code used for the segementation, which is moslty copy/pasted from Stardist doc examples:
```python
from __future__ import print_function, unicode_literals, absolute_import, division
import sys
import numpy as np
import matplotlib
matplotlib.rcParams["image.interpolation"] = None
import matplotlib.pyplot as plt
%matplotlib inline
%config InlineBackend.figure_format = 'retina'

from glob import glob
from cv2 import imread
from csbdeep.utils import Path, normalize
from csbdeep.io import save_tiff_imagej_compatible

from stardist import random_label_cmap, _draw_polygons, export_imagej_rois
from stardist.models import StarDist2D

np.random.seed(42)
lbl_cmap = random_label_cmap()
img = imread('HistoQuant/he_only/2173.jpg')

n_channel = 1 if img.ndim == 2 else img.shape[-1]
axis_norm = (0,1)   # normalize channels independently
# axis_norm = (0,1,2) # normalize channels jointly
if n_channel > 1:
    print("Normalizing image channels %s." % ('jointly' if axis_norm is None or 2 in axis_norm else 'independently'))
model_versatile = StarDist2D.from_pretrained('2D_versatile_he')
img_norm = normalize(img, 1,99.8, axis=axis_norm)
labels, details = model_versatile.predict_instances(img_norm)

plt.figure(figsize=(8,8))
plt.imshow(img_norm)
plt.axis('off');
plt.show()

plt.figure(figsize=(8,8))
plt.imshow(img_norm if img_norm.ndim==2 else img_norm[...,0], clim=(0,1), cmap='gray')
plt.imshow(labels, cmap=lbl_cmap, alpha=0.5)
plt.axis('off');
plt.show()
```

I wish to find a way to achieve the same performance using the Python version of Stardist. Could anyone help me with that ?

Thank you and have a nice day

**Comment by uschmidt83** [comment]
Hi @lambda-science, I cannot reproduce this. Also, you didn't read [the instructions](https://github.com/stardist/stardist/issues/new?assignees=&labels=&template=_1_question-help-support.md&title=) that refer to the image.sc forum for general questions like this.

```python
import numpy as np
import matplotlib
matplotlib.rcParams["image.interpolation"] = None
import matplotlib.pyplot as plt

from imageio import imread
from stardist import random_label_cmap
from stardist.models import StarDist2D

np.random.seed(42)
lbl_cmap = random_label_cmap()

img = imread('GBfJ2cn.jpeg')

print(img.min(), img.max())
img_norm = img / 255
print(img_norm.min(), img_norm.max())

model_versatile = StarDist2D.from_pretrained('2D_versatile_he')
labels, details = model_versatile.predict_instances(img_norm, nms_thresh=0.4, prob_thresh=0.5)

plt.figure(figsize=(8,8))
plt.imshow(img_norm)
plt.axis('off');
plt.show()

plt.figure(figsize=(8,8))
plt.imshow(labels, cmap=lbl_cmap)
plt.axis('off');
plt.show()
```
