### ISSUE TITLE
How did you create the MASK images? 

### ISSUE THREAD

**Issue by ghezalahmad** [stardist/stardist#203]
I have Microscopic image and I know how to split into train/test but how did you create the mask and what is the role of masked image?

Thank you for your nice work

**Comment by uschmidt83** [comment]
Hi @ghezalahmad, please follow the links [here](https://github.com/stardist/stardist/issues/new/choose) to find the documentation and FAQ. If your question isn't answered by that, please ask your question at the forum. We don't use GitHub issues for general support questions.
