### ISSUE TITLE
Error when importing stardist on macOS 10.13

### ISSUE THREAD

**Issue by ElpadoCan** [stardist/stardist#205]
**Describe the bug**
I cannot import stardist

**To reproduce**
Install stardist on macOS High Sierra v10.13.3 using conda --> import stardist

**Environment (please complete the following information):**
 - StarDist version [e.g. 0.8.3]
 - CSBDeep version [e.g. 0.7.2]
 - TensorFlow version [e.g. 2.5.3]
 - OS: macOS High Sierra v10.13.3
 - GPU memory (if applicable): not available

This is the error message that I get when running the suggested script
```
os: macOS-10.13.3-x86_64-i386-64bit
Traceback (most recent call last):
  File "/Users/guest/test.py", line 6, in <module>
    print(f'{m}: {importlib.import_module(m).__version__}')
  File "/Users/guest/opt/anaconda3/envs/test/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/guest/opt/anaconda3/envs/test/lib/python3.9/site-packages/stardist/__init__.py", line 15, in <module>
    from .geometry import star_dist,   polygons_to_label,   relabel_image_stardist, ray_angles, dist_to_coord
  File "/Users/guest/opt/anaconda3/envs/test/lib/python3.9/site-packages/stardist/geometry/__init__.py", line 5, in <module>
    from .geom2d import star_dist, relabel_image_stardist, ray_angles, dist_to_coord, polygons_to_label, polygons_to_label_coord
  File "/Users/guest/opt/anaconda3/envs/test/lib/python3.9/site-packages/stardist/geometry/geom2d.py", line 11, in <module>
    from ..lib.stardist2d import c_star_dist
ImportError: dlopen(/Users/guest/opt/anaconda3/envs/test/lib/python3.9/site-packages/stardist/lib/stardist2d.cpython-39-darwin.so, 2): Symbol not found: ____chkstk_darwin
  Referenced from: /Users/guest/opt/anaconda3/envs/test/lib/python3.9/site-packages/stardist/lib/../.dylibs/libomp.dylib (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib
 in /Users/guest/opt/anaconda3/envs/test/lib/python3.9/site-packages/stardist/lib/../.dylibs/libomp.dylib
```

**Comment by uschmidt83** [comment]
> **To reproduce** Install stardist on macOS High Sierra v10.13.3 using conda --> import stardist

Try to uninstall StarDist and then re-install it via pip (`pip install stardist`) instead of conda.

Do you happen to use a newer Mac with Apple Silicon, i.e. using an M1 or M2 CPU?
If so, the package on conda doesn't have the correct wheels.

**Comment by ElpadoCan** [comment]
My apologies I forgot to mention that I was already installing with pip in a conda environment. However, I already tried installing with pip on both python 3.8 and 3.9 in both a conda or venv environment.

The only thing I didn't try is to install with conda.

I don't have a Apple silicon. The other thing I need to try is to update to at least macos Mojave because I also had issues with the latest numba (while previous version worked).

**Comment by uschmidt83** [comment]
> Install stardist on macOS High Sierra v10.13.3

> The other thing I need to try is to update to at least macos Mojave

I only realized just now that your version of macOS is quite a bit too old. That's the reason why it's not working.


> Referenced from: /Users/guest/opt/anaconda3/envs/test/lib/python3.9/site-packages/stardist/lib/../.dylibs/libomp.dylib (which was built for Mac OS X 10.15)

Also see the error message, which indicates that you need at least macOS 10.15

**Comment by uschmidt83** [comment]
As a workaround, you could try to [build the StarDist wheel yourself](https://github.com/stardist/stardist/blob/master/README.md#installation-1).

**Comment by ElpadoCan** [comment]
Oh yeah, didn't read the error properly, sorry about that! My next try was to install macOS 10.15 without even knowing that it was actually the problem! Thanks!
