### ISSUE TITLE
How to interpret stardist.matching results?

### ISSUE THREAD

**Issue by fangpingmu** [stardist/stardist#206]
model = StarDist2D.from_pretrained('2D_versatile_he')

img_num = 0
img = X[img_num]
img = normalize(img, 1,99.8, axis=axis_norm)
labels, details = model.predict_instances(img) #,prob_thresh=0.4)

metrics =  matching(Y[img_num], labels)

print(metrics)

The image is the first MoNuSeg testing image. I don't perform any normalization. 

Matching(criterion='iou', thresh=0.5, fp=514, tp=57, fn=134, precision=0.09982486865148861, recall=0.29842931937172773, accuracy=0.08085106382978724, f1=0.14960629921259844, n_true=191, n_pred=571, mean_true_score=0.21061019498016198, mean_matched_score=0.7057288989686129, panoptic_quality=0.10558148882207595)

I cannot interpret the matching results. Precision, recall, accuracy, f1 are so low. When I view the prediction results (left is grand truth and right is prediction mask), the prediction looks good

<img width="827" alt="Screen Shot 2022-08-28 at 3 16 14 PM" src="https://user-images.githubusercontent.com/17434395/187091095-bd705456-a25f-481d-8c7a-62c788e3fa3a.png">
.

**Comment by uschmidt83** [comment]
Dear @fangpingmu, I'm sorry but this is a general question and not a bug report. Please ask this question [at the forum](https://forum.image.sc/tag/stardist), as [instructed](https://github.com/stardist/stardist/issues/new/choose).
