### ISSUE TITLE
TensorFlow check failed for large images

### ISSUE THREAD

**Issue by agclark12** [stardist/stardist#208]
Hi,

I am doing some 3D segmentation of nuclei using Stardist, and I have been running into some issues trying to make predictions on relatively large images. For training I was using smaller crops of my image stacks as suggested, and that all worked fine, and I am pretty happy with the prediction results for my validation and test images.

Now when I go back to do precitions the uncropped stacks (using a slightly modified version of the code in the example notebook), I am getting the following error:

`2022-09-01 11:26:04.798922: F tensorflow/stream_executor/cuda/cuda_dnn.cc:114] Check failed: narrow == wide (-792887296 vs. 3502080000)checked narrowing failed; values not equal post-conversion`

Based on [this discussion](https://stackoverflow.com/questions/53067722/tensorflow-error-checked-narrowing-failed-values-not-equal-post-conversion-ab) it seems like the second number in the parentheses (3502080000) indicates a number that is too big to be converted into a 32-bit int (max value 2147483647) and that this may have to do with the image size. After trying to multiply the image dimensions and bit depth in different ways, I cannot figure out how to arrive at this number, but it seems like from trying empirically that the threshold in terms of image size is about 63 million voxels (an image of 1200 x 1200 x 44 works, but 1200 x 1200 x 45 does not).

Is there any way I can avoid reducing the image size? If not, is there a specific voxel limit so I can try to rescale accordingly in the future? 

**Environment:
os: Windows-10-10.0.22000-SP0
stardist: 0.8.3
csbdeep: 0.7.2
tensorflow: 2.9.1
2022-09-01 14:10:47.122758: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1532] Created device /device:GPU:0 with 21626 MB memory:  -> device: 0, name: NVIDIA RTX A5000, pci bus id: 0000:01:00.0, compute capability: 8.6
tensorflow GPU: True

**Comment by uschmidt83** [comment]
Dear @agclark12, I'm sorry for the late reply, but this looks more like general need for help and not a bug report. Please ask questions like this [at the forum](https://forum.image.sc/tag/stardist), as [instructed](https://github.com/stardist/stardist/issues/new/choose).

(My first thought: Have you tried using `n_tiles` to predict large images? It's described in our example notebooks.)

**Comment by agclark12** [comment]
No worries. Sorry, you're right, not really a bug. Thanks for the tip on using `n_tiles`. I'll look into that and maybe post something in the forum. Anyway, thanks for the work you put into this. Really great piece of software!
