### ISSUE TITLE
Coordinates of labelled cell/objects 

### ISSUE THREAD

**Issue by Erfanahmed84** [stardist/stardist#215]
Dear Stardist

I am using StarDist2D.from_pretrained('2D_versatile_he') to label H&E images. Everything is alright, now i would like to add the coordinates of those labelled cell and want to create text file through regions props table. Could you please help in this regard.

**Comment by uschmidt83** [comment]
Dear @Erfanahmed84 , I'm sorry for the late reply, but this is a general need for help and not a bug report or feature request. Please ask questions like this [at the forum](https://forum.image.sc/tag/stardist), as [instructed](https://github.com/stardist/stardist/issues/new/choose).
