### ISSUE TITLE
Cannot suppress output of model.predict_instances(...)

### ISSUE THREAD

**Issue by ajinkya-kulkarni** [stardist/stardist#224]
**Describe the bug**
Cannot suppress the output of model.predict_instances(...)
Current output for the attached script:
```
Found model '2D_versatile_fluo' for 'StarDist2D'.
Loading network weights from 'weights_best.h5'.
Loading thresholds from 'thresholds.json'.
Using default values: prob_thresh=0.479071, nms_thresh=0.3.
```

**To reproduce**
```
from stardist.models import StarDist2D
from stardist.data import test_image_nuclei_2d
from stardist.plot import render_label
from csbdeep.utils import normalize

# creates a pretrained model
model = StarDist2D.from_pretrained('2D_versatile_fluo')
img = test_image_nuclei_2d()
labels, _ = model.predict_instances(normalize(img), predict_kwargs=dict(verbose=False))
# labels, _ = model.predict_instances(normalize(img), verbose = False)
```

**Expected behavior**
Ideally I want nothing to be displayed in the terminal

**Data and screenshots**
If applicable, add data (e.g. images) or screenshots to help explain your problem.

**Environment (please complete the following information):**
 - StarDist version [e.g. 0.6.2]
 - CSBDeep version [e.g. 0.6.1]
 - TensorFlow version [e.g. 2.3.1]
 - OS: [Windows, Linux, Mac]
 - GPU memory (if applicable): [e.g. 8 GB]

```
Python 3.10.9
macOS-10.16-x86_64-i386-64bit
stardist: 0.8.3
csbdeep: 0.7.3
tensorflow: 2.11.0
WARNING:tensorflow:From /Users/ajinkyakulkarni/Desktop/WSI-slide-segmentation/test.py:29: is_gpu_available (from tensorflow.python.framework.test_util) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.config.list_physical_devices('GPU')` instead.
tensorflow GPU: False
```

**Comment by maweigert** [comment]
Thanks for opening an issue! I would not call this a bug though, as a certain level of verbosity can be expected (changed the label from `bug` to `enhancement`)

**Comment by ajinkya-kulkarni** [comment]
But is there a way I can suppress everything? That way I can incorporate the model.predict_instances(...) in a larger pipeline.

**Comment by maweigert** [comment]
You could just redirect stdout, e.g. via `contextlib`:

```python 

import os 
from contextlib import redirect_stdout

with redirect_stdout(open(os.devnull, "w")) as f:
    model = StarDist2D.from_pretrained('2D_versatile_fluo')
    img = test_image_nuclei_2d()
    labels, _ = model.predict_instances(normalize(img), predict_kwargs=dict(verbose=False))
    # labels, _ = model.predict_instances(normalize(img), verbose = False)


```

**Comment by ajinkya-kulkarni** [comment]
Ahh didn't know that! Thanks a lot, it worked.
