### ISSUE TITLE
Support for Python 3.11

### ISSUE THREAD

**Issue by fluffygreenpillow** [stardist/stardist#227]
Hello, thank you for developing and continuing to maintain stardist in Python!

Is there a plan to support stardist for Python 3.11?

**Comment by uschmidt83** [comment]
Here's [the issue](https://github.com/numba/numba/issues/8841) that tracks the next numba release (candidate).

**Comment by uschmidt83** [comment]
Since the numba 0.57.0 has been released 2 days ago, StarDist now [works with Python 3.11](https://github.com/stardist/stardist/actions/runs/4880880857).

**Comment by petsuter** [comment]
Will stardist Python 3.11 wheels be uploaded to PyPI?

**Comment by uschmidt83** [comment]
@petsuter, we've made a new StarDist [release](https://github.com/stardist/stardist/releases) with wheels for Python 3.11.
