### ISSUE TITLE
`export_bioimageio()` generates a default dependency file not required by bioimage.io

### ISSUE THREAD

**Issue by qin-yu** [stardist/stardist#253]
The default behavior of `export_bioimageio()` is to generate an `environment.yaml` file, documenting the environment in which the function is executed. While this feature could prove beneficial to certain users, I believe it should be an optional aspect, especially considering that bioimage.io does not mandate it for TensorFlow models. 

Currently, a workaround for me involves specifying `"dependencies": None` in the `overwrite_spec_kwargs` dictionary. However, the existence of a default config file led me to take it for granted initially, resulting in unwanted reuploads and DOI records on Zenodo, and unnecessary installation of environments for bioimage.io's CI on GitHub. Additionally, even if an update is made without the `environment.yaml` file, the file persists and must be manually deleted. 

To streamline the export process and enhance clarity for new users, I suggest adding a parameter, such as `generate_default_deps=False`, allowing users to opt out of this feature by default while retaining the option for those who find it valuable.

PS: A bug in generated `environment.yaml` file has been reported into #252

**Comment by uschmidt83** [comment]
Let's discuss this in #254

**Comment by uschmidt83** [comment]
Fixed by #254
