### ISSUE TITLE
The segmentation results with the same StarDist2D are different on different machines

### ISSUE THREAD

**Issue by ccalafiore** [stardist/stardist#274]
**Describe the bug**

I run the same code on my laptop and on an HPC (High Performance Computing) to segment the same images. While the results are excellent when the code runs on my laptop and on a CPU node of the HPC, they are very very bad when the same code runs on a GPU node of the HPC. 

For example, when I segment this raw image below on my laptop and on a CPU node of the HPC

![raw_image](https://github.com/stardist/stardist/assets/44749641/a4171e98-effd-4d09-864f-291a52ecddc4)

I get these very good results

![segmented_image_with_StarDist2D_on_cpu_of_windows_laptop](https://github.com/stardist/stardist/assets/44749641/5cc4c4af-4663-4d82-aebb-2da1e1f59de8)

However, when I run the same code on the same image on a GPU of the same HPC, I get these very bad results below.

![segmented_image_with_StarDist2D_on_gpu_of_linux_HPC](https://github.com/stardist/stardist/assets/44749641/5f1d6d7b-5137-4007-a701-ed6f6d2064f8)

**To reproduce**

Here is the code that I run.

```python
import skimage
import os
import platform
from stardist.models import StarDist2D
from stardist import random_label_cmap
from csbdeep.utils import normalize
import matplotlib.pyplot as plt


format_input_image = 'tif'
format_output_image = 'png'

input_image_name = 'raw_image'
output_image_name = 'segmented_image_with_StarDist2D'

axis_norm = (0, 1)

os_name = platform.system()

if os_name == 'Windows':
    output_image_name = output_image_name + '_on_cpu_of_windows_laptop'
elif os_name == 'Linux':
    output_image_name = output_image_name + '_on_cpu_of_linux_HPC'


file_path_input_image = os.path.join(input_image_name + '.' + format_input_image)

image = skimage.io.imread(file_path_input_image, plugin="tifffile")  # shape is (283, 257) (x, y)
image = normalize(image, 1,99.8, axis=axis_norm)

model = StarDist2D.from_pretrained('2D_demo')

mask, details = model.predict_instances(image)

lbl_cmap = random_label_cmap(n=mask.max() + 1)

plt.figure(num=0, figsize=(8, 8), dpi=150)
plt.imshow(image, clim=(0, 1), cmap='gray')
plt.axis('off')
plt.tight_layout()
plt.savefig(input_image_name + '.' + format_output_image, format=format_output_image)

plt.figure(num=1, figsize=(8, 8), dpi=150)
plt.imshow(mask, cmap=lbl_cmap)
plt.axis('off')
plt.tight_layout()
plt.savefig(output_image_name + '.' + format_output_image, format=format_output_image)
```

**Expected behavior**
The output segmented image on the GPU node of the HPC shold be as good as on my laptop and on the CPU node of the same HPC.

**Data and screenshots**

The zip file contains the code, the input raw image, and output segmented images on my laptop, CPU node and GPU node of the HPC
[code.zip](https://github.com/user-attachments/files/16018054/code.zip)

**Environment**

I ran this code below on my laptop, on a CPU node of the HPC and on a GPU node of the HPC.

```python
import importlib, platform

print(f'os: {platform.platform()}')
for m in ('stardist','csbdeep','tensorflow'):
    try:
        print(f'{m}: {importlib.import_module(m).__version__}')
    except ModuleNotFoundError:
        print(f'{m}: not installed')

import tensorflow as tf
try:
    print(f'tensorflow GPU: {tf.test.is_gpu_available()}')
except:
    print(f'tensorflow GPU: {tf.config.list_physical_devices("GPU")}')
```

On my laptop, it prints this:
- stardist: 0.8.5
- csbdeep: 0.7.4
- tensorflow: 2.16.1
- os: Windows-10-10.0.22621-SP0
- tensorflow GPU: False

On the CPU node, it prints this:
- stardist: 0.9.1
- csbdeep: 0.8.0
- tensorflow: 2.16.1
- os: Linux-3.10.0-693.90.2.el7.x86_64-x86_64-with-glibc2.17
- tensorflow GPU: False

On the GPU node, it prints this:
- stardist: 0.9.1
- csbdeep: 0.8.0
- tensorflow: 2.16.1
- os: Linux-3.10.0-1160.90.1.el7.x86_64-x86_64-with-glibc2.17
- tensorflow GPU: True

**Comment by maweigert** [comment]
Hi @ccalafiore 

thanks for taking the time to write such a detailed bug report including the example - this makes it so much easier to follow along! 

Unfortunately, I cannot reproduce this and both CPU and GPU predictions look similar to your "good" case on my machine. So I suspect this is something specific to your hpc GPU setup.

Could you run the following on the HPC node

```python 
import skimage
import numpy as np
from stardist.models import StarDist2D
from csbdeep.utils import normalize

image = skimage.io.imread('raw_image.tif', plugin="tifffile")  
image = normalize(image, 1,99.8)

model = StarDist2D.from_pretrained('2D_demo')

p, d = model.predict(image)

mask, details = model.predict_instances(image)

print(f'\n\nmodel  {np.mean(model.keras_model.layers[1].weights[0]):.8f}')
print(f'p       {np.mean(p):.8f}')
print(f'd       {np.mean(d):.8f}')
```

and see whether the printed numbers are similar?

```
model  -0.00548911
p       0.02589413
d       3.16523814
``` 

Btw, you probably want to use the `2D_versatile_fluo` model rather than the `2D_demo` model...

**Comment by ccalafiore** [comment]
Hi, @maweigert,

I have rerun the code with the `2D_versatile_fluo` model rather than the `2D_demo` model and got similar results.

here is the new code:

```python

import skimage
import os
import platform
from stardist.models import StarDist2D
from stardist import random_label_cmap
from csbdeep.utils import normalize
import matplotlib.pyplot as plt
import tensorflow as tf


format_input_image = 'tif'
format_output_image = 'png'

input_image_name = 'raw_image'
output_image_name = 'segmented_image_with_StarDist2D'

axis_norm = (0, 1)

if tf.test.is_gpu_available():
    node_name = 'gpu'
else:
    node_name = 'cpu'

os_name = platform.system()
if os_name == 'Windows':
    output_image_name = output_image_name + '_on_' + node_name + '_of_windows_laptop'
elif os_name == 'Linux':
    output_image_name = output_image_name + '_on_' + node_name + '_of_linux_HPC'


file_path_input_image = os.path.join(input_image_name + '.' + format_input_image)

image = skimage.io.imread(file_path_input_image, plugin="tifffile")  # shape is (283, 257) (x, y)
image = normalize(image, 1,99.8, axis=axis_norm)

model = StarDist2D.from_pretrained('2D_versatile_fluo')

mask, details = model.predict_instances(image)

print(mask.min(), mask.max())

lbl_cmap = random_label_cmap(n=mask.max() + 1)

plt.figure(num=0, figsize=(8, 8), dpi=150)
plt.imshow(image, clim=(0, 1), cmap='gray')
plt.axis('off')
plt.tight_layout()
plt.savefig(input_image_name + '.' + format_output_image, format=format_output_image)

plt.figure(num=1, figsize=(8, 8), dpi=150)
plt.imshow(mask, cmap=lbl_cmap)
plt.axis('off')
plt.tight_layout()
plt.savefig(output_image_name + '.' + format_output_image, format=format_output_image)
```


I get these good results on the laptop and on the CPU node of the HPC.

![segmented_image_with_StarDist2D_on_cpu_of_windows_laptop](https://github.com/stardist/stardist/assets/44749641/e7e6cf0e-80a5-4d69-ba69-1e4cac587aaf)

However, I get bad results on the GPU node of the HPC.

![segmented_image_with_StarDist2D_on_gpu_of_linux_HPC](https://github.com/stardist/stardist/assets/44749641/6c005391-2be5-45f3-9be5-804fc25e011e)

I noticed the results on the GPU node of the HPC are always different every time I rerun the code. They are always bad at every rerun, but they are also different. For instance, these are the results of another run with the same code and GPU node.

![segmented_image_with_StarDist2D_on_gpu_of_linux_HPC](https://github.com/stardist/stardist/assets/44749641/16d65ac5-e10e-462a-b955-a70ea0f86e76)

**Comment by maweigert** [comment]
Ye,s looks like your cuda+GPU setup is somehow broken. Did you try to run the code snippet I posted before?

**Comment by ccalafiore** [comment]
Hi @maweigert, I am going to run your code now on with both` 2D_versatile_fluo` and `2D_demo` models

**Comment by ccalafiore** [comment]
By the way, if it helps, this is how I set up the stardist environment on the GPU node.

```
conda create --name stardist python=3.11
conda activate stardist
python -m pip install --upgrade pip
python -m pip install tensorflow[and-cuda]
python -m pip install stardist csbdeep scikit-image numpy gputools
```

**Comment by maweigert** [comment]
what are the numpy versions for your different setups?

**Comment by ccalafiore** [comment]
The numpy version is `1.24.4` on my laptop and `1.23.5` on both the CPU and GPU nodes of the HPC.

**Comment by ccalafiore** [comment]
I ran your code, @maweigert.

It's the same on my laptop and on the CPU node of the HPC:

```
model  -0.00548911
p       0.02589363
d       3.16550326
```

It's different on the GPU node of the HPC:

```
model  -0.00548911
p       0.89220500
d       119.36746979
```

**Comment by maweigert** [comment]
Ok, so its seems like an issue with the core tensorflow operations being broken. You could try to downgrade to tensorflow==2.15 ...

**Comment by ccalafiore** [comment]
The GPU node prints this message: "Default CUDA version on this node is 12.1". Which version should CUDA be?

**Comment by ccalafiore** [comment]
`python -m pip install tensorflow==2.15` is to install the CPU version. How to install the GPU version? Both `python -m pip install tensorflow[and-cuda]==2.15` and `python -m pip install tensorflow==2.15[and-cuda]` do not work.

**Comment by ccalafiore** [comment]
I first tried to run this command `python -m pip install tensorflow[and-cuda]` and then `python -m pip install tensorflow==2.15`. I got no errors, but the original segmentation issue is still unresolved.

**Comment by ccalafiore** [comment]
It was a CUDA problem on the HPC. The HPC manager installed a new conda environment that works.

**Comment by ccalafiore** [comment]
It was a CUDA problem on the HPC. The HPC manager installed a new conda environment that works.
