### ISSUE TITLE
Url for QuPath plugin broken

### ISSUE THREAD

**Issue by camilla31** [stardist/stardist#279]
When I try to access the documentation for installing a QuPath plug in via this link I get a 404: https://qupath.readthedocs.io/en/latest/docs/advanced/stardist.html

Help would be highly appreciated. Thank you!

Camilla

**Comment by uschmidt83** [comment]
Hi @camilla31, the new link is https://qupath.readthedocs.io/en/latest/docs/deep/stardist.html.
I've already fixed it in the documentation.

**Comment by camilla31** [comment]
Thank you very much for your help
