### ISSUE TITLE
Export imageJ ROIs for 3D polyhedra

### ISSUE THREAD

**Issue by michaelschwimmer** [stardist/stardist#37]
Hi!

I'm a complete beginner at Python but find the software really exciting, so have jumped in at the deep end! I'm still familiarising myself with the pipeline in 3D using the demo 3D model and have run through the Jupyter notebooks and I think it is all working. 

My aim is to be able to export the label maps and visualise them in ImageJ or something similar, and to use the 3 dimensional ROIs to calculate values for nuclear volume and shape and other things. I can see that you've made a notebook to export the ROIs for the 2D model prediction into FIJI which works great for me. I tried to adapt this for 3D by just having axes set to zyx and having 'dist' instead of 'coord' (in export_imagej_rois('img_rois.zip', details['dist'])). I have found that this doesn't really work, but not sure why.

 I also tried to export the demo 3d model into deepImageJ, but it runs into trouble when you try to apply it to an image. I can give more details, but as I am quite lost I'm not sure what is the relevant information. 

I would appreciate any help, 
Best wishes from a coding newbie, always in awe

Michael Schwimmer

**Comment by uschmidt83** [comment]
> I'm a complete beginner at Python but find the software really exciting, so have jumped in at the deep end!

Glad that you like it!

> My aim is to be able to export the label maps and visualise them in ImageJ or something similar, and to use the 3 dimensional ROIs to calculate values for nuclear volume and shape and other things.

I suggest you do the prediction in Python to get the label image, which you can then import in Fiji with the [3D Roi Manager](https://imagejdocu.tudor.lu/plugin/stacks/3d_roi_manager/start) (installation instructions [here](https://imagejdocu.tudor.lu/plugin/stacks/3d_ij_suite/start#installation)). This should work well, as long as you don't have (strongly) overlapping predictions or it's not important to you to get the complete shapes for all objects.

> I can see that you've made a notebook to export the ROIs for the 2D model prediction into FIJI which works great for me. I tried to adapt this for 3D by just having axes set to zyx and having 'dist' instead of 'coord' (in export_imagej_rois('img_rois.zip', details['dist'])). I have found that this doesn't really work, but not sure why.

This function only works for 2D polygons and cannot be simply adapted for 3D.
 
> I also tried to export the demo 3d model into deepImageJ, but it runs into trouble when you try to apply it to an image. I can give more details, but as I am quite lost I'm not sure what is the relevant information.

It's not that simple and even if it worked, this won't get you 3D ROIs in Fiji. Our [StarDist Fiji plugin](https://imagej.net/StarDist) currently only works in 2D because it's not that easy to support 3D... but we hope to get this done eventually.

Best,
Uwe

**Comment by michaelschwimmer** [comment]
Thank you for your quick reply! 

> I suggest you do the prediction in Python to get the label image, which you can then import in Fiji with the [3D Roi Manager](https://imagejdocu.tudor.lu/plugin/stacks/3d_roi_manager/start) (installation instructions [here](https://imagejdocu.tudor.lu/plugin/stacks/3d_ij_suite/start#installation)). This should work well, as long as you don't have (strongly) overlapping predictions or it's not important to you to get the complete shapes for all objects.

This sounds really good. Apologies if this is a bit of a starter question but would I just save the label image as a tiff file and then open it in FIJI, and then segment it with the 3D ROI viewer? 

> It's not that simple and even if it worked, this won't get you 3D ROIs in Fiji. Our [StarDist Fiji plugin](https://imagej.net/StarDist) currently only works in 2D because it's not that easy to support 3D... but we hope to get this done eventually.

Ah I thought it wouldn't be simple. The error message I was getting was that the input tensor had to be 5 dimensional, and was wondering whether the mismatch was due to tensor organisation convention of NHWC not including a third spatial dimension. 

The images you have from paintera look really beautiful, I think that is my aim here, but perhaps FIJI's 3d viewer of the 3d ROIs would get something similar?

Thanks again!!

Michael Schwimmer

**Comment by uschmidt83** [comment]
> This sounds really good. I do have quite overlapping nuclei though unfortunately. Apologies if this is a bit of a starter question but would I just save the label image as a tiff file and then open it in FIJI, and then segment it with the 3D ROI viewer?

You can just "add" the label image in the 3D Roi Manager and it should recognize all the object instances.

> The images you have from paintera look really beautiful, I think that is my aim here, but perhaps FIJI's 3d viewer of the 3d ROIs would get something similar?

Use the 3D Roi Manager for measurements (area, etc.). It uses Fiji's 3D viewer for visualization, but it doesn't look at pretty as [paintera](https://github.com/saalfeldlab/paintera) or [napari](https://github.com/napari/napari).

**Comment by jackyko1991** [comment]
Hi,

I am working on 3D segmentation dataset and would like to export the Stardist result similar to the documentation plot:
![image](https://github.com/stardist/stardist/raw/master/images/overview_3d.png)

I understand that 3D polyhedra output is different from the 2D one. From the output dictionary, I discover the polyhedra is described by `distance`, `points`, `prob`, `rays`, `rays_vertices`, `rays_faces`

Can this be saved to 3D objects like `vtp` format or give some documented explanation on the output file?

In particular, the `rays` object `Rays_GoldenSpiral_anisotropy_2.00_1.00_1.00_n_96` is self-explanatory for file saving, while others are numpy arrays

**Comment by maweigert** [comment]
You can export the predicted polyhedra to an `obj` file via `export_to_obj_file3D` if that is what you want?

```python
from csbdeep.utils import normalize
from stardist.data import test_image_nuclei_3d
from stardist.models import StarDist3D
from stardist.geometry import export_to_obj_file3D

x = test_image_nuclei_3d()
model = StarDist3D.from_pretrained('3D_demo')
labels, polys = model.predict_instances(normalize(x))

export_to_obj_file3D(polys, 'mypolys.obj')
```

**Comment by jackyko1991** [comment]
@maweigert  I have tested your code to export the obj file.

Unable to open the exported obj file with any viewer including [3dviewer](https://3dviewer.net/) and Paraview.

**Comment by maweigert** [comment]
It should work with blender, didn't try with any other tool yet.

**Comment by jackyko1991** [comment]
@maweigert It works after re-exporting with Blender.

But the exported obj file only contains vertices but not the cell centroids, corresponding rays, ray faces and cell ids. Is there any help to visualize them?

**Comment by maweigert** [comment]
> Is there any help to visualize them?

Unfortunately not. I think I used matplotlibs `mplot3d` for the paper figure.
