### ISSUE TITLE
Data generator for large datasets

### ISSUE THREAD

**Issue by nalinratnayeke** [stardist/stardist#57]
Hi StarDist team,

Great work with this tool! I haven't seen anything that works as well as this and the accessible tutorials and codebase are a big plus. I just had a couple of questions/comments about the implementation of data generators in StarDist. 

I might be mistaken here, but based on the tutorial and looking at the data generator you are using, it seems as though you have to load all training data into a variable to train the model, and the generator is just used for augmentation and cropping. In the case where the training dataset is too large to fit into memory, what would you recommend? I've seen data generators used to stream data directly from a directory to alleviate this problem (though it can bottleneck the training process if read speed is too slow). Based on results I've seen for this tool, extremely large training datasets may not be necessary to achieve good performance, but it's a little hard to tell until you try it out. This also could be useful at prediction time, when processing large datasets without explicitly splitting and loading data into batches. 

Also in general keras.fit_generator can be run multithreaded, but I think it is not in the current build of StarDist.  Are there considerations that make it advisable not to allow it run it in that way? In the past this has also sped up the collection of data into memory when reading from a directory. 

I think the relevant part is here:
https://github.com/mpicbg-csbd/stardist/blob/22d2ae27ea8a52c4438ae54081da8421c7ced3e4/stardist/models/model2d.py#L376-L378

Best,
Nalin

**Comment by maweigert** [comment]
> Great work with this tool! I haven't seen anything that works as well as this and the accessible tutorials and codebase are a big plus.

Thanks, very much appreciated! :)

>  In the case where the training dataset is too large to fit into memory, what would you recommend? 

So far all of our datasets did fit into memory, so I haven't encountered that problem yet (is this the case for you?).
An easy workaround would be to define the training data `X` and `Y`  as [`keras.utils.Sequence`](https://keras.io/api/utils/python_utils/#sequence-class) generator which could load the data lazily on demand.  Afterwards `model.train(X,Y,...)` should work as usual.

> Also in general keras.fit_generator can be run multithreaded, but I think it is not in the current build. Are there considerations that make it advisable not to run it in that way?

We already use OpenMP to parallelise the radial distance computation during batch generation  - so having an additional multithreaded data loader would probably not result in much improvement.

**Comment by nalinratnayeke** [comment]
Thanks for the quick response - ah yes your suggestion makes total sense. We have some training datasets that have >1000 images ~2000 x ~2000, so depending on the system it can exceed memory. However, in our previous experience the full dataset was probably much larger than it needed to be so it might not be a problem in this case. 

And actually while I bring up the image size, another consideration I was thinking about was in terms of input image size, my understanding is that the training generator takes "patches" out of the image to accommodate GPU memory constraints. Does this essentially amount to a random crop of the image which changes each epoch? Or is a single image split into multiple patches that are then used to train so that each epoch the whole image is seen by the network?

**Comment by maweigert** [comment]
> 1000 images ~2000 x ~2000, so depending on the system it can exceed memory.

Yeah, that is pretty large :) (Short reminder, that the objects have to fit into the field of view of the network, which by default is 92x92 pixels). 


> Does this essentially amount to a random crop of the image which changes each epoch? Or is a single image split into multiple patches that are then used to train so that each epoch the whole image is seen by the network?

The former, i.e. for every image a random crop of `patch_size` is extracted. Additionally image regions that contain labels will be preferentially sampled (the probability with which this is done can be changed with the parameter `config.train_foreground_only`).

**Comment by nalinratnayeke** [comment]
Perfect, thanks for the clarifications and I'm excited to try this out more thoroughly.

**Comment by Optimox** [comment]
Hello,

I'm facing the same issue, all my data can not fit in RAM (I have 3D images and total training set > > 100Go).

I've been trying `keras.utils.Sequence` as suggested by @maweigert, my idea is to simply replace a list of numpy arrays with a Sequence class that loads images on the fly.

```
from tensorflow.keras.utils import Sequence
from tifffile import imread

class DataLoader(Sequence):
    
    def __init__(self, path_list, mode):
        self.x, self.mode = path_list, mode
        
        #retro compatibility with numpy
        self.ndim=3
        if mode == "Y":
            self.dtype = np.int
        else:
            self.dtype = np.float
            
    def __len__(self):
        return len(self.x)

    def __getitem__(self, idx):
        
        filename = self.x[idx]
        if self.mode == "X":
            return imread(filename) / 255
        else:
            return imread(filename)
```

I'm actually able to launch a training with batch size of 1 without specifying anisotropy and things seem to run ok (note that I had to add `dtype` and `ndim` to make things work and that I have some problems in my pipeline as explained bellow).

However some part of my training pipeline are broken:

- when running this to compute anisotropy `extents = calculate_extents(Y)` I first get this warning
```_asarray.py (83): Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray```
and after a few seconds of computation the code fails with this error message :
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-14-36ac39a79e87> in <module>
----> 1 extents = calculate_extents(Y)
      2 anisotropy = tuple(np.max(extents) / extents)
      3 print('empirical anisotropy of labeled objects = %s' % str(anisotropy))

/work/.cache/poetry/kc-segmentation-DJpFP61h-py3.7/lib/python3.7/site-packages/stardist/utils.py in calculate_extents(lbl, func)
    165     n in (2,3) or _raise(ValueError("label image should be 2- or 3-dimensional (or pass a list of these)"))
    166 
--> 167     regs = regionprops(lbl)
    168     if len(regs) == 0:
    169         return np.zeros(n)

/work/.cache/poetry/kc-segmentation-DJpFP61h-py3.7/lib/python3.7/site-packages/skimage/measure/_regionprops.py in regionprops(label_image, intensity_image, cache, coordinates)
    883     regions = []
    884 
--> 885     objects = ndi.find_objects(label_image)
    886     for i, sl in enumerate(objects):
    887         if sl is None:

/work/.cache/poetry/kc-segmentation-DJpFP61h-py3.7/lib/python3.7/site-packages/scipy/ndimage/measurements.py in find_objects(input, max_label)
    301 
    302     if max_label < 1:
--> 303         max_label = input.max()
    304 
    305     return _nd_image.find_objects(input, max_label)

/work/.cache/poetry/kc-segmentation-DJpFP61h-py3.7/lib/python3.7/site-packages/numpy/core/_methods.py in _amax(a, axis, out, keepdims, initial, where)
     37 def _amax(a, axis=None, out=None, keepdims=False,
     38           initial=_NoValue, where=True):
---> 39     return umr_maximum(a, axis, None, out, keepdims, initial, where)
     40 
     41 def _amin(a, axis=None, out=None, keepdims=False,

ValueError: operands could not be broadcast together with shapes (80,330,500) (85,400,500)
```
I think maybe somehow my new class is considered as one large numpy array and not as a list of numpy arrays, is that possible? Any idea how to overcome this? 

- if I switch to a batch size of 2, training does not work anymore and I end up with this error:
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-21-54ffb4970400> in <module>
      3             augmenter=augmenter_fn(ZOOM_RATIO, ZOOM_PROB),
      4             epochs=200, #100,
----> 5             seed=42)

/work/.cache/poetry/kc-segmentation-DJpFP61h-py3.7/lib/python3.7/site-packages/stardist/models/model3d.py in train(self, X, Y, validation_data, augmenter, seed, epochs, steps_per_epoch, workers)
    480                       callbacks=self.callbacks, verbose=1,
    481                       # set validation batchsize to training batchsize (only works in tf 2.x)
--> 482                       **(dict(validation_batch_size = self.config.train_batch_size) if _tf_version_at_least("2.2.0") else {}))
    483 
    484         self._training_finished()

/work/.cache/poetry/kc-segmentation-DJpFP61h-py3.7/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py in _method_wrapper(self, *args, **kwargs)
     64   def _method_wrapper(self, *args, **kwargs):
     65     if not self._in_multi_worker_mode():  # pylint: disable=protected-access
---> 66       return method(self, *args, **kwargs)
     67 
     68     # Running inside `run_distribute_coordinator` already.

/work/.cache/poetry/kc-segmentation-DJpFP61h-py3.7/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py in fit(self, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, validation_batch_size, validation_freq, max_queue_size, workers, use_multiprocessing)
    813           workers=workers,
    814           use_multiprocessing=use_multiprocessing,
--> 815           model=self)
    816 
    817       # Container that configures and calls `tf.keras.Callback`s.

/work/.cache/poetry/kc-segmentation-DJpFP61h-py3.7/lib/python3.7/site-packages/tensorflow/python/keras/engine/data_adapter.py in __init__(self, x, y, sample_weight, batch_size, steps_per_epoch, initial_epoch, epochs, shuffle, class_weight, max_queue_size, workers, use_multiprocessing, model)
   1110         use_multiprocessing=use_multiprocessing,
   1111         distribution_strategy=ds_context.get_strategy(),
-> 1112         model=model)
   1113 
   1114     strategy = ds_context.get_strategy()

/work/.cache/poetry/kc-segmentation-DJpFP61h-py3.7/lib/python3.7/site-packages/tensorflow/python/keras/engine/data_adapter.py in __init__(self, x, y, sample_weights, workers, use_multiprocessing, max_queue_size, model, **kwargs)
    770     # Since we have to know the dtype of the python generator when we build the
    771     # dataset, we have to look at a batch to infer the structure.
--> 772     peek, x = self._peek_and_restore(x)
    773     assert_not_namedtuple(peek)
    774     peek = self._standardize_batch(peek)

/work/.cache/poetry/kc-segmentation-DJpFP61h-py3.7/lib/python3.7/site-packages/tensorflow/python/keras/engine/data_adapter.py in _peek_and_restore(x)
    828   @staticmethod
    829   def _peek_and_restore(x):
--> 830     peek = next(x)
    831     return peek, itertools.chain([peek], x)
    832 

/work/.cache/poetry/kc-segmentation-DJpFP61h-py3.7/lib/python3.7/site-packages/csbdeep/internals/train.py in __iter__(self)
    112         # print(f"### __iter__", flush=True)
    113         for i in range(len(self)):
--> 114             yield self[i]
    115 
    116     def batch(self, i):

/work/.cache/poetry/kc-segmentation-DJpFP61h-py3.7/lib/python3.7/site-packages/stardist/models/model3d.py in __getitem__(self, i)
     64             X = X[0][np.newaxis]
     65         else:
---> 66             X = np.stack(X, out=self.out_X[:len(Y)])
     67         if X.ndim == 4: # input image has no channel axis
     68             X = np.expand_dims(X,-1)

<__array_function__ internals> in stack(*args, **kwargs)

/work/.cache/poetry/kc-segmentation-DJpFP61h-py3.7/lib/python3.7/site-packages/numpy/core/shape_base.py in stack(arrays, axis, out)
    425     shapes = {arr.shape for arr in arrays}
    426     if len(shapes) != 1:
--> 427         raise ValueError('all input arrays must have the same shape')
    428 
    429     result_ndim = arrays[0].ndim + 1

ValueError: all input arrays must have the same shape
```
So it looks like again there is a problem with shapes being different, as if the `train_path_size` did not work.

Do you have any idea how to solve this?

Thank you very much,

Bests

**Comment by maweigert** [comment]
Hi, 

Could you provide a minimal example that shows both things failing? E.g. a simple way could be to have the data generator create random numpy arrays instead of reading files in `__getitem__`

**Comment by Optimox** [comment]
Sure thing, thanks for asking.

Let's create some random 3D images and random masks:

```
import numpy as np
def random_image(shape):
    """
    just a random imaga
    """
    return np.random.randint(0, 255, shape)

def diag_mask(shape, n_cells=3, cell_size=2, cell_dist=5):
    """
    Labels with cells on the diagonal
    """
    mask = np.zeros(shape, dtype=np.int16)
    for cell_id in range(1, n_cells+1):
        center_pos = cell_id*cell_dist
        mask[center_pos-cell_size:center_pos+cell_size,
             center_pos-cell_size:center_pos+cell_size,
             center_pos-cell_size:center_pos+cell_size,
             ] = cell_id
    return mask
    
```

The dataloader now would look like this :
```
class DataLoader(Sequence):
    
    def __init__(self, shapes_list, mode):
        self.x, self.mode = shapes_list, mode
        
        #retro compatibility with numpy
        self.ndim=3
        if mode == "Y":
            self.dtype = np.int
        else:
            self.dtype = np.float
            
    def __len__(self):
        return len(self.x)

    def __getitem__(self, idx):
        
        shape = self.x[idx]
        if self.mode == "X":
            return random_image(shape)
        else:
            return diag_mask(shape)
```

Now if I try to create two synthetic datasets, one with always same shapes and one with different shapes : 
```
SHAPES_DIFF = [(100, 100, 100), (110, 190, 90), (100, 100, 110), (110, 100, 100), (100, 110, 100)]

SHAPES_SAME = [(100, 100, 100)]*5

X_DIFF = DataLoader(SHAPES_DIFF, mode="X")
Y_DIFF = DataLoader(SHAPES_DIFF, mode="Y")

X_SAME = DataLoader(SHAPES_SAME, mode="X")
Y_SAME = DataLoader(SHAPES_SAME, mode="Y")
```

Then running this `extents = calculate_extents(Y_DIFF)` returns this error :
 `ValueError: operands could not be broadcast together with shapes (100,100,100) (110,190,90) `

While running this `extents = calculate_extents(Y_SAME)` runs just fine.

I think this small synthetic example is enough to reproduce my problem.

**Comment by maweigert** [comment]
Ok, thanks! 

Can you install the `dev` branch and see whether the issue persists (adjust the name of your gcc/g++ below)?

```CC=gcc-10 CXX=g++-10 pip install git+https://github.com/stardist/stardist@dev```

**Comment by Optimox** [comment]
not sure about what you meant about `CC=gcc-10 CXX=g++-10` but I installed the dev branch by running `pip install git+https://github.com/stardist/stardist@dev` and it indeed seems to solve the problem!

Thank you very much for the super fast response and help!
May I ask if you have any idea when the next release on pypi might happen?

**Comment by uschmidt83** [comment]
> May I ask if you have any idea when the next release on pypi might happen?

Sorry, we don't yet have a date for the next release.

In the meantime, you could simply re-define the function that Martin changed. E.g. paste this in your script/notebook (after you imported `calculate_extents` from stardist):

```python
def calculate_extents(lbl, func=np.median):
    """ Aggregate bounding box sizes of objects in label images. """

    import numpy as np
    from collections.abc import Iterable
    from csbdeep.utils import _raise
    from skimage.measure import regionprops
    
    if (isinstance(lbl,np.ndarray) and lbl.ndim==4) or (not isinstance(lbl,np.ndarray) and  isinstance(lbl,Iterable)):
        return func(np.stack([calculate_extents(_lbl,func) for _lbl in lbl], axis=0), axis=0)

    n = lbl.ndim
    n in (2,3) or _raise(ValueError("label image should be 2- or 3-dimensional (or pass a list of these)"))

    regs = regionprops(lbl)
    if len(regs) == 0:
        return np.zeros(n)
    else:
        extents = np.array([np.array(r.bbox[n:])-np.array(r.bbox[:n]) for r in regs])
        return func(extents, axis=0)
```

**Comment by Optimox** [comment]
@uschmidt83 Thank you very much I can go with that in the meantime!

**Comment by uschmidt83** [comment]
Hi @Optimox, the latest release (0.7.2) fixes this issue and is now on PyPI.
